name: neonize
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.0

# Add regular dependencies here.
dependencies:
  protobuf: ^4.1.0
  ffi: ^2.1.4
  logging: ^1.3.0
  ansicolor: ^2.0.3
  qr: ^3.0.2
  crypto: ^3.0.6
  fixnum: ^1.1.1
  mime_type: ^1.0.1
  image: ^4.5.4
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
