//
//  Generated code. Do not modify.
//  source: waWeb/WAWebProtobufsWeb.proto
//
// @dart = 3.3

// ignore_for_file: annotate_overrides, camel_case_types, comment_references
// ignore_for_file: constant_identifier_names
// ignore_for_file: curly_braces_in_flow_control_structures
// ignore_for_file: deprecated_member_use_from_same_package, library_prefixes
// ignore_for_file: non_constant_identifier_names

import 'dart:convert' as $convert;
import 'dart:core' as $core;
import 'dart:typed_data' as $typed_data;

@$core.Deprecated('Use webMessageInfoDescriptor instead')
const WebMessageInfo$json = {
  '1': 'WebMessageInfo',
  '2': [
    {'1': 'key', '3': 1, '4': 2, '5': 11, '6': '.WACommon.MessageKey', '10': 'key'},
    {'1': 'message', '3': 2, '4': 1, '5': 11, '6': '.WAWebProtobufsE2E.Message', '10': 'message'},
    {'1': 'messageTimestamp', '3': 3, '4': 1, '5': 4, '10': 'messageTimestamp'},
    {'1': 'status', '3': 4, '4': 1, '5': 14, '6': '.WAWebProtobufsWeb.WebMessageInfo.Status', '10': 'status'},
    {'1': 'participant', '3': 5, '4': 1, '5': 9, '10': 'participant'},
    {'1': 'messageC2STimestamp', '3': 6, '4': 1, '5': 4, '10': 'messageC2STimestamp'},
    {'1': 'ignore', '3': 16, '4': 1, '5': 8, '10': 'ignore'},
    {'1': 'starred', '3': 17, '4': 1, '5': 8, '10': 'starred'},
    {'1': 'broadcast', '3': 18, '4': 1, '5': 8, '10': 'broadcast'},
    {'1': 'pushName', '3': 19, '4': 1, '5': 9, '10': 'pushName'},
    {'1': 'mediaCiphertextSHA256', '3': 20, '4': 1, '5': 12, '10': 'mediaCiphertextSHA256'},
    {'1': 'multicast', '3': 21, '4': 1, '5': 8, '10': 'multicast'},
    {'1': 'urlText', '3': 22, '4': 1, '5': 8, '10': 'urlText'},
    {'1': 'urlNumber', '3': 23, '4': 1, '5': 8, '10': 'urlNumber'},
    {'1': 'messageStubType', '3': 24, '4': 1, '5': 14, '6': '.WAWebProtobufsWeb.WebMessageInfo.StubType', '10': 'messageStubType'},
    {'1': 'clearMedia', '3': 25, '4': 1, '5': 8, '10': 'clearMedia'},
    {'1': 'messageStubParameters', '3': 26, '4': 3, '5': 9, '10': 'messageStubParameters'},
    {'1': 'duration', '3': 27, '4': 1, '5': 13, '10': 'duration'},
    {'1': 'labels', '3': 28, '4': 3, '5': 9, '10': 'labels'},
    {'1': 'paymentInfo', '3': 29, '4': 1, '5': 11, '6': '.WAWebProtobufsWeb.PaymentInfo', '10': 'paymentInfo'},
    {'1': 'finalLiveLocation', '3': 30, '4': 1, '5': 11, '6': '.WAWebProtobufsE2E.LiveLocationMessage', '10': 'finalLiveLocation'},
    {'1': 'quotedPaymentInfo', '3': 31, '4': 1, '5': 11, '6': '.WAWebProtobufsWeb.PaymentInfo', '10': 'quotedPaymentInfo'},
    {'1': 'ephemeralStartTimestamp', '3': 32, '4': 1, '5': 4, '10': 'ephemeralStartTimestamp'},
    {'1': 'ephemeralDuration', '3': 33, '4': 1, '5': 13, '10': 'ephemeralDuration'},
    {'1': 'ephemeralOffToOn', '3': 34, '4': 1, '5': 8, '10': 'ephemeralOffToOn'},
    {'1': 'ephemeralOutOfSync', '3': 35, '4': 1, '5': 8, '10': 'ephemeralOutOfSync'},
    {'1': 'bizPrivacyStatus', '3': 36, '4': 1, '5': 14, '6': '.WAWebProtobufsWeb.WebMessageInfo.BizPrivacyStatus', '10': 'bizPrivacyStatus'},
    {'1': 'verifiedBizName', '3': 37, '4': 1, '5': 9, '10': 'verifiedBizName'},
    {'1': 'mediaData', '3': 38, '4': 1, '5': 11, '6': '.WAWebProtobufsWeb.MediaData', '10': 'mediaData'},
    {'1': 'photoChange', '3': 39, '4': 1, '5': 11, '6': '.WAWebProtobufsWeb.PhotoChange', '10': 'photoChange'},
    {'1': 'userReceipt', '3': 40, '4': 3, '5': 11, '6': '.WAWebProtobufsWeb.UserReceipt', '10': 'userReceipt'},
    {'1': 'reactions', '3': 41, '4': 3, '5': 11, '6': '.WAWebProtobufsWeb.Reaction', '10': 'reactions'},
    {'1': 'quotedStickerData', '3': 42, '4': 1, '5': 11, '6': '.WAWebProtobufsWeb.MediaData', '10': 'quotedStickerData'},
    {'1': 'futureproofData', '3': 43, '4': 1, '5': 12, '10': 'futureproofData'},
    {'1': 'statusPsa', '3': 44, '4': 1, '5': 11, '6': '.WAWebProtobufsWeb.StatusPSA', '10': 'statusPsa'},
    {'1': 'pollUpdates', '3': 45, '4': 3, '5': 11, '6': '.WAWebProtobufsWeb.PollUpdate', '10': 'pollUpdates'},
    {'1': 'pollAdditionalMetadata', '3': 46, '4': 1, '5': 11, '6': '.WAWebProtobufsWeb.PollAdditionalMetadata', '10': 'pollAdditionalMetadata'},
    {'1': 'agentID', '3': 47, '4': 1, '5': 9, '10': 'agentID'},
    {'1': 'statusAlreadyViewed', '3': 48, '4': 1, '5': 8, '10': 'statusAlreadyViewed'},
    {'1': 'messageSecret', '3': 49, '4': 1, '5': 12, '10': 'messageSecret'},
    {'1': 'keepInChat', '3': 50, '4': 1, '5': 11, '6': '.WAWebProtobufsWeb.KeepInChat', '10': 'keepInChat'},
    {'1': 'originalSelfAuthorUserJIDString', '3': 51, '4': 1, '5': 9, '10': 'originalSelfAuthorUserJIDString'},
    {'1': 'revokeMessageTimestamp', '3': 52, '4': 1, '5': 4, '10': 'revokeMessageTimestamp'},
    {'1': 'pinInChat', '3': 54, '4': 1, '5': 11, '6': '.WAWebProtobufsWeb.PinInChat', '10': 'pinInChat'},
    {'1': 'premiumMessageInfo', '3': 55, '4': 1, '5': 11, '6': '.WAWebProtobufsWeb.PremiumMessageInfo', '10': 'premiumMessageInfo'},
    {'1': 'is1PBizBotMessage', '3': 56, '4': 1, '5': 8, '10': 'is1PBizBotMessage'},
    {'1': 'isGroupHistoryMessage', '3': 57, '4': 1, '5': 8, '10': 'isGroupHistoryMessage'},
    {'1': 'botMessageInvokerJID', '3': 58, '4': 1, '5': 9, '10': 'botMessageInvokerJID'},
    {'1': 'commentMetadata', '3': 59, '4': 1, '5': 11, '6': '.WAWebProtobufsWeb.CommentMetadata', '10': 'commentMetadata'},
    {'1': 'eventResponses', '3': 61, '4': 3, '5': 11, '6': '.WAWebProtobufsWeb.EventResponse', '10': 'eventResponses'},
    {'1': 'reportingTokenInfo', '3': 62, '4': 1, '5': 11, '6': '.WAWebProtobufsWeb.ReportingTokenInfo', '10': 'reportingTokenInfo'},
    {'1': 'newsletterServerID', '3': 63, '4': 1, '5': 4, '10': 'newsletterServerID'},
    {'1': 'eventAdditionalMetadata', '3': 64, '4': 1, '5': 11, '6': '.WAWebProtobufsWeb.EventAdditionalMetadata', '10': 'eventAdditionalMetadata'},
    {'1': 'isMentionedInStatus', '3': 65, '4': 1, '5': 8, '10': 'isMentionedInStatus'},
    {'1': 'statusMentions', '3': 66, '4': 3, '5': 9, '10': 'statusMentions'},
    {'1': 'targetMessageID', '3': 67, '4': 1, '5': 11, '6': '.WACommon.MessageKey', '10': 'targetMessageID'},
    {'1': 'messageAddOns', '3': 68, '4': 3, '5': 11, '6': '.WAWebProtobufsWeb.MessageAddOn', '10': 'messageAddOns'},
    {'1': 'statusMentionMessageInfo', '3': 69, '4': 1, '5': 11, '6': '.WAWebProtobufsWeb.StatusMentionMessage', '10': 'statusMentionMessageInfo'},
    {'1': 'isSupportAiMessage', '3': 70, '4': 1, '5': 8, '10': 'isSupportAiMessage'},
    {'1': 'statusMentionSources', '3': 71, '4': 3, '5': 9, '10': 'statusMentionSources'},
    {'1': 'supportAiCitations', '3': 72, '4': 3, '5': 11, '6': '.WAWebProtobufsWeb.Citation', '10': 'supportAiCitations'},
    {'1': 'botTargetID', '3': 73, '4': 1, '5': 9, '10': 'botTargetID'},
  ],
  '4': [WebMessageInfo_BizPrivacyStatus$json, WebMessageInfo_StubType$json, WebMessageInfo_Status$json],
};

@$core.Deprecated('Use webMessageInfoDescriptor instead')
const WebMessageInfo_BizPrivacyStatus$json = {
  '1': 'BizPrivacyStatus',
  '2': [
    {'1': 'E2EE', '2': 0},
    {'1': 'FB', '2': 2},
    {'1': 'BSP', '2': 1},
    {'1': 'BSP_AND_FB', '2': 3},
  ],
};

@$core.Deprecated('Use webMessageInfoDescriptor instead')
const WebMessageInfo_StubType$json = {
  '1': 'StubType',
  '2': [
    {'1': 'UNKNOWN', '2': 0},
    {'1': 'REVOKE', '2': 1},
    {'1': 'CIPHERTEXT', '2': 2},
    {'1': 'FUTUREPROOF', '2': 3},
    {'1': 'NON_VERIFIED_TRANSITION', '2': 4},
    {'1': 'UNVERIFIED_TRANSITION', '2': 5},
    {'1': 'VERIFIED_TRANSITION', '2': 6},
    {'1': 'VERIFIED_LOW_UNKNOWN', '2': 7},
    {'1': 'VERIFIED_HIGH', '2': 8},
    {'1': 'VERIFIED_INITIAL_UNKNOWN', '2': 9},
    {'1': 'VERIFIED_INITIAL_LOW', '2': 10},
    {'1': 'VERIFIED_INITIAL_HIGH', '2': 11},
    {'1': 'VERIFIED_TRANSITION_ANY_TO_NONE', '2': 12},
    {'1': 'VERIFIED_TRANSITION_ANY_TO_HIGH', '2': 13},
    {'1': 'VERIFIED_TRANSITION_HIGH_TO_LOW', '2': 14},
    {'1': 'VERIFIED_TRANSITION_HIGH_TO_UNKNOWN', '2': 15},
    {'1': 'VERIFIED_TRANSITION_UNKNOWN_TO_LOW', '2': 16},
    {'1': 'VERIFIED_TRANSITION_LOW_TO_UNKNOWN', '2': 17},
    {'1': 'VERIFIED_TRANSITION_NONE_TO_LOW', '2': 18},
    {'1': 'VERIFIED_TRANSITION_NONE_TO_UNKNOWN', '2': 19},
    {'1': 'GROUP_CREATE', '2': 20},
    {'1': 'GROUP_CHANGE_SUBJECT', '2': 21},
    {'1': 'GROUP_CHANGE_ICON', '2': 22},
    {'1': 'GROUP_CHANGE_INVITE_LINK', '2': 23},
    {'1': 'GROUP_CHANGE_DESCRIPTION', '2': 24},
    {'1': 'GROUP_CHANGE_RESTRICT', '2': 25},
    {'1': 'GROUP_CHANGE_ANNOUNCE', '2': 26},
    {'1': 'GROUP_PARTICIPANT_ADD', '2': 27},
    {'1': 'GROUP_PARTICIPANT_REMOVE', '2': 28},
    {'1': 'GROUP_PARTICIPANT_PROMOTE', '2': 29},
    {'1': 'GROUP_PARTICIPANT_DEMOTE', '2': 30},
    {'1': 'GROUP_PARTICIPANT_INVITE', '2': 31},
    {'1': 'GROUP_PARTICIPANT_LEAVE', '2': 32},
    {'1': 'GROUP_PARTICIPANT_CHANGE_NUMBER', '2': 33},
    {'1': 'BROADCAST_CREATE', '2': 34},
    {'1': 'BROADCAST_ADD', '2': 35},
    {'1': 'BROADCAST_REMOVE', '2': 36},
    {'1': 'GENERIC_NOTIFICATION', '2': 37},
    {'1': 'E2E_IDENTITY_CHANGED', '2': 38},
    {'1': 'E2E_ENCRYPTED', '2': 39},
    {'1': 'CALL_MISSED_VOICE', '2': 40},
    {'1': 'CALL_MISSED_VIDEO', '2': 41},
    {'1': 'INDIVIDUAL_CHANGE_NUMBER', '2': 42},
    {'1': 'GROUP_DELETE', '2': 43},
    {'1': 'GROUP_ANNOUNCE_MODE_MESSAGE_BOUNCE', '2': 44},
    {'1': 'CALL_MISSED_GROUP_VOICE', '2': 45},
    {'1': 'CALL_MISSED_GROUP_VIDEO', '2': 46},
    {'1': 'PAYMENT_CIPHERTEXT', '2': 47},
    {'1': 'PAYMENT_FUTUREPROOF', '2': 48},
    {'1': 'PAYMENT_TRANSACTION_STATUS_UPDATE_FAILED', '2': 49},
    {'1': 'PAYMENT_TRANSACTION_STATUS_UPDATE_REFUNDED', '2': 50},
    {'1': 'PAYMENT_TRANSACTION_STATUS_UPDATE_REFUND_FAILED', '2': 51},
    {'1': 'PAYMENT_TRANSACTION_STATUS_RECEIVER_PENDING_SETUP', '2': 52},
    {'1': 'PAYMENT_TRANSACTION_STATUS_RECEIVER_SUCCESS_AFTER_HICCUP', '2': 53},
    {'1': 'PAYMENT_ACTION_ACCOUNT_SETUP_REMINDER', '2': 54},
    {'1': 'PAYMENT_ACTION_SEND_PAYMENT_REMINDER', '2': 55},
    {'1': 'PAYMENT_ACTION_SEND_PAYMENT_INVITATION', '2': 56},
    {'1': 'PAYMENT_ACTION_REQUEST_DECLINED', '2': 57},
    {'1': 'PAYMENT_ACTION_REQUEST_EXPIRED', '2': 58},
    {'1': 'PAYMENT_ACTION_REQUEST_CANCELLED', '2': 59},
    {'1': 'BIZ_VERIFIED_TRANSITION_TOP_TO_BOTTOM', '2': 60},
    {'1': 'BIZ_VERIFIED_TRANSITION_BOTTOM_TO_TOP', '2': 61},
    {'1': 'BIZ_INTRO_TOP', '2': 62},
    {'1': 'BIZ_INTRO_BOTTOM', '2': 63},
    {'1': 'BIZ_NAME_CHANGE', '2': 64},
    {'1': 'BIZ_MOVE_TO_CONSUMER_APP', '2': 65},
    {'1': 'BIZ_TWO_TIER_MIGRATION_TOP', '2': 66},
    {'1': 'BIZ_TWO_TIER_MIGRATION_BOTTOM', '2': 67},
    {'1': 'OVERSIZED', '2': 68},
    {'1': 'GROUP_CHANGE_NO_FREQUENTLY_FORWARDED', '2': 69},
    {'1': 'GROUP_V4_ADD_INVITE_SENT', '2': 70},
    {'1': 'GROUP_PARTICIPANT_ADD_REQUEST_JOIN', '2': 71},
    {'1': 'CHANGE_EPHEMERAL_SETTING', '2': 72},
    {'1': 'E2E_DEVICE_CHANGED', '2': 73},
    {'1': 'VIEWED_ONCE', '2': 74},
    {'1': 'E2E_ENCRYPTED_NOW', '2': 75},
    {'1': 'BLUE_MSG_BSP_FB_TO_BSP_PREMISE', '2': 76},
    {'1': 'BLUE_MSG_BSP_FB_TO_SELF_FB', '2': 77},
    {'1': 'BLUE_MSG_BSP_FB_TO_SELF_PREMISE', '2': 78},
    {'1': 'BLUE_MSG_BSP_FB_UNVERIFIED', '2': 79},
    {'1': 'BLUE_MSG_BSP_FB_UNVERIFIED_TO_SELF_PREMISE_VERIFIED', '2': 80},
    {'1': 'BLUE_MSG_BSP_FB_VERIFIED', '2': 81},
    {'1': 'BLUE_MSG_BSP_FB_VERIFIED_TO_SELF_PREMISE_UNVERIFIED', '2': 82},
    {'1': 'BLUE_MSG_BSP_PREMISE_TO_SELF_PREMISE', '2': 83},
    {'1': 'BLUE_MSG_BSP_PREMISE_UNVERIFIED', '2': 84},
    {'1': 'BLUE_MSG_BSP_PREMISE_UNVERIFIED_TO_SELF_PREMISE_VERIFIED', '2': 85},
    {'1': 'BLUE_MSG_BSP_PREMISE_VERIFIED', '2': 86},
    {'1': 'BLUE_MSG_BSP_PREMISE_VERIFIED_TO_SELF_PREMISE_UNVERIFIED', '2': 87},
    {'1': 'BLUE_MSG_CONSUMER_TO_BSP_FB_UNVERIFIED', '2': 88},
    {'1': 'BLUE_MSG_CONSUMER_TO_BSP_PREMISE_UNVERIFIED', '2': 89},
    {'1': 'BLUE_MSG_CONSUMER_TO_SELF_FB_UNVERIFIED', '2': 90},
    {'1': 'BLUE_MSG_CONSUMER_TO_SELF_PREMISE_UNVERIFIED', '2': 91},
    {'1': 'BLUE_MSG_SELF_FB_TO_BSP_PREMISE', '2': 92},
    {'1': 'BLUE_MSG_SELF_FB_TO_SELF_PREMISE', '2': 93},
    {'1': 'BLUE_MSG_SELF_FB_UNVERIFIED', '2': 94},
    {'1': 'BLUE_MSG_SELF_FB_UNVERIFIED_TO_SELF_PREMISE_VERIFIED', '2': 95},
    {'1': 'BLUE_MSG_SELF_FB_VERIFIED', '2': 96},
    {'1': 'BLUE_MSG_SELF_FB_VERIFIED_TO_SELF_PREMISE_UNVERIFIED', '2': 97},
    {'1': 'BLUE_MSG_SELF_PREMISE_TO_BSP_PREMISE', '2': 98},
    {'1': 'BLUE_MSG_SELF_PREMISE_UNVERIFIED', '2': 99},
    {'1': 'BLUE_MSG_SELF_PREMISE_VERIFIED', '2': 100},
    {'1': 'BLUE_MSG_TO_BSP_FB', '2': 101},
    {'1': 'BLUE_MSG_TO_CONSUMER', '2': 102},
    {'1': 'BLUE_MSG_TO_SELF_FB', '2': 103},
    {'1': 'BLUE_MSG_UNVERIFIED_TO_BSP_FB_VERIFIED', '2': 104},
    {'1': 'BLUE_MSG_UNVERIFIED_TO_BSP_PREMISE_VERIFIED', '2': 105},
    {'1': 'BLUE_MSG_UNVERIFIED_TO_SELF_FB_VERIFIED', '2': 106},
    {'1': 'BLUE_MSG_UNVERIFIED_TO_VERIFIED', '2': 107},
    {'1': 'BLUE_MSG_VERIFIED_TO_BSP_FB_UNVERIFIED', '2': 108},
    {'1': 'BLUE_MSG_VERIFIED_TO_BSP_PREMISE_UNVERIFIED', '2': 109},
    {'1': 'BLUE_MSG_VERIFIED_TO_SELF_FB_UNVERIFIED', '2': 110},
    {'1': 'BLUE_MSG_VERIFIED_TO_UNVERIFIED', '2': 111},
    {'1': 'BLUE_MSG_BSP_FB_UNVERIFIED_TO_BSP_PREMISE_VERIFIED', '2': 112},
    {'1': 'BLUE_MSG_BSP_FB_UNVERIFIED_TO_SELF_FB_VERIFIED', '2': 113},
    {'1': 'BLUE_MSG_BSP_FB_VERIFIED_TO_BSP_PREMISE_UNVERIFIED', '2': 114},
    {'1': 'BLUE_MSG_BSP_FB_VERIFIED_TO_SELF_FB_UNVERIFIED', '2': 115},
    {'1': 'BLUE_MSG_SELF_FB_UNVERIFIED_TO_BSP_PREMISE_VERIFIED', '2': 116},
    {'1': 'BLUE_MSG_SELF_FB_VERIFIED_TO_BSP_PREMISE_UNVERIFIED', '2': 117},
    {'1': 'E2E_IDENTITY_UNAVAILABLE', '2': 118},
    {'1': 'GROUP_CREATING', '2': 119},
    {'1': 'GROUP_CREATE_FAILED', '2': 120},
    {'1': 'GROUP_BOUNCED', '2': 121},
    {'1': 'BLOCK_CONTACT', '2': 122},
    {'1': 'EPHEMERAL_SETTING_NOT_APPLIED', '2': 123},
    {'1': 'SYNC_FAILED', '2': 124},
    {'1': 'SYNCING', '2': 125},
    {'1': 'BIZ_PRIVACY_MODE_INIT_FB', '2': 126},
    {'1': 'BIZ_PRIVACY_MODE_INIT_BSP', '2': 127},
    {'1': 'BIZ_PRIVACY_MODE_TO_FB', '2': 128},
    {'1': 'BIZ_PRIVACY_MODE_TO_BSP', '2': 129},
    {'1': 'DISAPPEARING_MODE', '2': 130},
    {'1': 'E2E_DEVICE_FETCH_FAILED', '2': 131},
    {'1': 'ADMIN_REVOKE', '2': 132},
    {'1': 'GROUP_INVITE_LINK_GROWTH_LOCKED', '2': 133},
    {'1': 'COMMUNITY_LINK_PARENT_GROUP', '2': 134},
    {'1': 'COMMUNITY_LINK_SIBLING_GROUP', '2': 135},
    {'1': 'COMMUNITY_LINK_SUB_GROUP', '2': 136},
    {'1': 'COMMUNITY_UNLINK_PARENT_GROUP', '2': 137},
    {'1': 'COMMUNITY_UNLINK_SIBLING_GROUP', '2': 138},
    {'1': 'COMMUNITY_UNLINK_SUB_GROUP', '2': 139},
    {'1': 'GROUP_PARTICIPANT_ACCEPT', '2': 140},
    {'1': 'GROUP_PARTICIPANT_LINKED_GROUP_JOIN', '2': 141},
    {'1': 'COMMUNITY_CREATE', '2': 142},
    {'1': 'EPHEMERAL_KEEP_IN_CHAT', '2': 143},
    {'1': 'GROUP_MEMBERSHIP_JOIN_APPROVAL_REQUEST', '2': 144},
    {'1': 'GROUP_MEMBERSHIP_JOIN_APPROVAL_MODE', '2': 145},
    {'1': 'INTEGRITY_UNLINK_PARENT_GROUP', '2': 146},
    {'1': 'COMMUNITY_PARTICIPANT_PROMOTE', '2': 147},
    {'1': 'COMMUNITY_PARTICIPANT_DEMOTE', '2': 148},
    {'1': 'COMMUNITY_PARENT_GROUP_DELETED', '2': 149},
    {'1': 'COMMUNITY_LINK_PARENT_GROUP_MEMBERSHIP_APPROVAL', '2': 150},
    {'1': 'GROUP_PARTICIPANT_JOINED_GROUP_AND_PARENT_GROUP', '2': 151},
    {'1': 'MASKED_THREAD_CREATED', '2': 152},
    {'1': 'MASKED_THREAD_UNMASKED', '2': 153},
    {'1': 'BIZ_CHAT_ASSIGNMENT', '2': 154},
    {'1': 'CHAT_PSA', '2': 155},
    {'1': 'CHAT_POLL_CREATION_MESSAGE', '2': 156},
    {'1': 'CAG_MASKED_THREAD_CREATED', '2': 157},
    {'1': 'COMMUNITY_PARENT_GROUP_SUBJECT_CHANGED', '2': 158},
    {'1': 'CAG_INVITE_AUTO_ADD', '2': 159},
    {'1': 'BIZ_CHAT_ASSIGNMENT_UNASSIGN', '2': 160},
    {'1': 'CAG_INVITE_AUTO_JOINED', '2': 161},
    {'1': 'SCHEDULED_CALL_START_MESSAGE', '2': 162},
    {'1': 'COMMUNITY_INVITE_RICH', '2': 163},
    {'1': 'COMMUNITY_INVITE_AUTO_ADD_RICH', '2': 164},
    {'1': 'SUB_GROUP_INVITE_RICH', '2': 165},
    {'1': 'SUB_GROUP_PARTICIPANT_ADD_RICH', '2': 166},
    {'1': 'COMMUNITY_LINK_PARENT_GROUP_RICH', '2': 167},
    {'1': 'COMMUNITY_PARTICIPANT_ADD_RICH', '2': 168},
    {'1': 'SILENCED_UNKNOWN_CALLER_AUDIO', '2': 169},
    {'1': 'SILENCED_UNKNOWN_CALLER_VIDEO', '2': 170},
    {'1': 'GROUP_MEMBER_ADD_MODE', '2': 171},
    {'1': 'GROUP_MEMBERSHIP_JOIN_APPROVAL_REQUEST_NON_ADMIN_ADD', '2': 172},
    {'1': 'COMMUNITY_CHANGE_DESCRIPTION', '2': 173},
    {'1': 'SENDER_INVITE', '2': 174},
    {'1': 'RECEIVER_INVITE', '2': 175},
    {'1': 'COMMUNITY_ALLOW_MEMBER_ADDED_GROUPS', '2': 176},
    {'1': 'PINNED_MESSAGE_IN_CHAT', '2': 177},
    {'1': 'PAYMENT_INVITE_SETUP_INVITER', '2': 178},
    {'1': 'PAYMENT_INVITE_SETUP_INVITEE_RECEIVE_ONLY', '2': 179},
    {'1': 'PAYMENT_INVITE_SETUP_INVITEE_SEND_AND_RECEIVE', '2': 180},
    {'1': 'LINKED_GROUP_CALL_START', '2': 181},
    {'1': 'REPORT_TO_ADMIN_ENABLED_STATUS', '2': 182},
    {'1': 'EMPTY_SUBGROUP_CREATE', '2': 183},
    {'1': 'SCHEDULED_CALL_CANCEL', '2': 184},
    {'1': 'SUBGROUP_ADMIN_TRIGGERED_AUTO_ADD_RICH', '2': 185},
    {'1': 'GROUP_CHANGE_RECENT_HISTORY_SHARING', '2': 186},
    {'1': 'PAID_MESSAGE_SERVER_CAMPAIGN_ID', '2': 187},
    {'1': 'GENERAL_CHAT_CREATE', '2': 188},
    {'1': 'GENERAL_CHAT_ADD', '2': 189},
    {'1': 'GENERAL_CHAT_AUTO_ADD_DISABLED', '2': 190},
    {'1': 'SUGGESTED_SUBGROUP_ANNOUNCE', '2': 191},
    {'1': 'BIZ_BOT_1P_MESSAGING_ENABLED', '2': 192},
    {'1': 'CHANGE_USERNAME', '2': 193},
    {'1': 'BIZ_COEX_PRIVACY_INIT_SELF', '2': 194},
    {'1': 'BIZ_COEX_PRIVACY_TRANSITION_SELF', '2': 195},
    {'1': 'SUPPORT_AI_EDUCATION', '2': 196},
    {'1': 'BIZ_BOT_3P_MESSAGING_ENABLED', '2': 197},
    {'1': 'REMINDER_SETUP_MESSAGE', '2': 198},
    {'1': 'REMINDER_SENT_MESSAGE', '2': 199},
    {'1': 'REMINDER_CANCEL_MESSAGE', '2': 200},
    {'1': 'BIZ_COEX_PRIVACY_INIT', '2': 201},
    {'1': 'BIZ_COEX_PRIVACY_TRANSITION', '2': 202},
    {'1': 'GROUP_DEACTIVATED', '2': 203},
    {'1': 'COMMUNITY_DEACTIVATE_SIBLING_GROUP', '2': 204},
    {'1': 'EVENT_UPDATED', '2': 205},
    {'1': 'EVENT_CANCELED', '2': 206},
    {'1': 'COMMUNITY_OWNER_UPDATED', '2': 207},
    {'1': 'COMMUNITY_SUB_GROUP_VISIBILITY_HIDDEN', '2': 208},
    {'1': 'CAPI_GROUP_NE2EE_SYSTEM_MESSAGE', '2': 209},
    {'1': 'STATUS_MENTION', '2': 210},
    {'1': 'USER_CONTROLS_SYSTEM_MESSAGE', '2': 211},
    {'1': 'SUPPORT_SYSTEM_MESSAGE', '2': 212},
    {'1': 'CHANGE_LID', '2': 213},
    {'1': 'BIZ_CUSTOMER_3PD_DATA_SHARING_OPT_IN_MESSAGE', '2': 214},
    {'1': 'BIZ_CUSTOMER_3PD_DATA_SHARING_OPT_OUT_MESSAGE', '2': 215},
    {'1': 'CHANGE_LIMIT_SHARING', '2': 216},
    {'1': 'GROUP_MEMBER_LINK_MODE', '2': 217},
  ],
};

@$core.Deprecated('Use webMessageInfoDescriptor instead')
const WebMessageInfo_Status$json = {
  '1': 'Status',
  '2': [
    {'1': 'ERROR', '2': 0},
    {'1': 'PENDING', '2': 1},
    {'1': 'SERVER_ACK', '2': 2},
    {'1': 'DELIVERY_ACK', '2': 3},
    {'1': 'READ', '2': 4},
    {'1': 'PLAYED', '2': 5},
  ],
};

/// Descriptor for `WebMessageInfo`. Decode as a `google.protobuf.DescriptorProto`.
final $typed_data.Uint8List webMessageInfoDescriptor = $convert.base64Decode(
    'Cg5XZWJNZXNzYWdlSW5mbxImCgNrZXkYASACKAsyFC5XQUNvbW1vbi5NZXNzYWdlS2V5UgNrZX'
    'kSNAoHbWVzc2FnZRgCIAEoCzIaLldBV2ViUHJvdG9idWZzRTJFLk1lc3NhZ2VSB21lc3NhZ2US'
    'KgoQbWVzc2FnZVRpbWVzdGFtcBgDIAEoBFIQbWVzc2FnZVRpbWVzdGFtcBJACgZzdGF0dXMYBC'
    'ABKA4yKC5XQVdlYlByb3RvYnVmc1dlYi5XZWJNZXNzYWdlSW5mby5TdGF0dXNSBnN0YXR1cxIg'
    'CgtwYXJ0aWNpcGFudBgFIAEoCVILcGFydGljaXBhbnQSMAoTbWVzc2FnZUMyU1RpbWVzdGFtcB'
    'gGIAEoBFITbWVzc2FnZUMyU1RpbWVzdGFtcBIWCgZpZ25vcmUYECABKAhSBmlnbm9yZRIYCgdz'
    'dGFycmVkGBEgASgIUgdzdGFycmVkEhwKCWJyb2FkY2FzdBgSIAEoCFIJYnJvYWRjYXN0EhoKCH'
    'B1c2hOYW1lGBMgASgJUghwdXNoTmFtZRI0ChVtZWRpYUNpcGhlcnRleHRTSEEyNTYYFCABKAxS'
    'FW1lZGlhQ2lwaGVydGV4dFNIQTI1NhIcCgltdWx0aWNhc3QYFSABKAhSCW11bHRpY2FzdBIYCg'
    'd1cmxUZXh0GBYgASgIUgd1cmxUZXh0EhwKCXVybE51bWJlchgXIAEoCFIJdXJsTnVtYmVyElQK'
    'D21lc3NhZ2VTdHViVHlwZRgYIAEoDjIqLldBV2ViUHJvdG9idWZzV2ViLldlYk1lc3NhZ2VJbm'
    'ZvLlN0dWJUeXBlUg9tZXNzYWdlU3R1YlR5cGUSHgoKY2xlYXJNZWRpYRgZIAEoCFIKY2xlYXJN'
    'ZWRpYRI0ChVtZXNzYWdlU3R1YlBhcmFtZXRlcnMYGiADKAlSFW1lc3NhZ2VTdHViUGFyYW1ldG'
    'VycxIaCghkdXJhdGlvbhgbIAEoDVIIZHVyYXRpb24SFgoGbGFiZWxzGBwgAygJUgZsYWJlbHMS'
    'QAoLcGF5bWVudEluZm8YHSABKAsyHi5XQVdlYlByb3RvYnVmc1dlYi5QYXltZW50SW5mb1ILcG'
    'F5bWVudEluZm8SVAoRZmluYWxMaXZlTG9jYXRpb24YHiABKAsyJi5XQVdlYlByb3RvYnVmc0Uy'
    'RS5MaXZlTG9jYXRpb25NZXNzYWdlUhFmaW5hbExpdmVMb2NhdGlvbhJMChFxdW90ZWRQYXltZW'
    '50SW5mbxgfIAEoCzIeLldBV2ViUHJvdG9idWZzV2ViLlBheW1lbnRJbmZvUhFxdW90ZWRQYXlt'
    'ZW50SW5mbxI4ChdlcGhlbWVyYWxTdGFydFRpbWVzdGFtcBggIAEoBFIXZXBoZW1lcmFsU3Rhcn'
    'RUaW1lc3RhbXASLAoRZXBoZW1lcmFsRHVyYXRpb24YISABKA1SEWVwaGVtZXJhbER1cmF0aW9u'
    'EioKEGVwaGVtZXJhbE9mZlRvT24YIiABKAhSEGVwaGVtZXJhbE9mZlRvT24SLgoSZXBoZW1lcm'
    'FsT3V0T2ZTeW5jGCMgASgIUhJlcGhlbWVyYWxPdXRPZlN5bmMSXgoQYml6UHJpdmFjeVN0YXR1'
    'cxgkIAEoDjIyLldBV2ViUHJvdG9idWZzV2ViLldlYk1lc3NhZ2VJbmZvLkJpelByaXZhY3lTdG'
    'F0dXNSEGJpelByaXZhY3lTdGF0dXMSKAoPdmVyaWZpZWRCaXpOYW1lGCUgASgJUg92ZXJpZmll'
    'ZEJpek5hbWUSOgoJbWVkaWFEYXRhGCYgASgLMhwuV0FXZWJQcm90b2J1ZnNXZWIuTWVkaWFEYX'
    'RhUgltZWRpYURhdGESQAoLcGhvdG9DaGFuZ2UYJyABKAsyHi5XQVdlYlByb3RvYnVmc1dlYi5Q'
    'aG90b0NoYW5nZVILcGhvdG9DaGFuZ2USQAoLdXNlclJlY2VpcHQYKCADKAsyHi5XQVdlYlByb3'
    'RvYnVmc1dlYi5Vc2VyUmVjZWlwdFILdXNlclJlY2VpcHQSOQoJcmVhY3Rpb25zGCkgAygLMhsu'
    'V0FXZWJQcm90b2J1ZnNXZWIuUmVhY3Rpb25SCXJlYWN0aW9ucxJKChFxdW90ZWRTdGlja2VyRG'
    'F0YRgqIAEoCzIcLldBV2ViUHJvdG9idWZzV2ViLk1lZGlhRGF0YVIRcXVvdGVkU3RpY2tlckRh'
    'dGESKAoPZnV0dXJlcHJvb2ZEYXRhGCsgASgMUg9mdXR1cmVwcm9vZkRhdGESOgoJc3RhdHVzUH'
    'NhGCwgASgLMhwuV0FXZWJQcm90b2J1ZnNXZWIuU3RhdHVzUFNBUglzdGF0dXNQc2ESPwoLcG9s'
    'bFVwZGF0ZXMYLSADKAsyHS5XQVdlYlByb3RvYnVmc1dlYi5Qb2xsVXBkYXRlUgtwb2xsVXBkYX'
    'RlcxJhChZwb2xsQWRkaXRpb25hbE1ldGFkYXRhGC4gASgLMikuV0FXZWJQcm90b2J1ZnNXZWIu'
    'UG9sbEFkZGl0aW9uYWxNZXRhZGF0YVIWcG9sbEFkZGl0aW9uYWxNZXRhZGF0YRIYCgdhZ2VudE'
    'lEGC8gASgJUgdhZ2VudElEEjAKE3N0YXR1c0FscmVhZHlWaWV3ZWQYMCABKAhSE3N0YXR1c0Fs'
    'cmVhZHlWaWV3ZWQSJAoNbWVzc2FnZVNlY3JldBgxIAEoDFINbWVzc2FnZVNlY3JldBI9CgprZW'
    'VwSW5DaGF0GDIgASgLMh0uV0FXZWJQcm90b2J1ZnNXZWIuS2VlcEluQ2hhdFIKa2VlcEluQ2hh'
    'dBJICh9vcmlnaW5hbFNlbGZBdXRob3JVc2VySklEU3RyaW5nGDMgASgJUh9vcmlnaW5hbFNlbG'
    'ZBdXRob3JVc2VySklEU3RyaW5nEjYKFnJldm9rZU1lc3NhZ2VUaW1lc3RhbXAYNCABKARSFnJl'
    'dm9rZU1lc3NhZ2VUaW1lc3RhbXASOgoJcGluSW5DaGF0GDYgASgLMhwuV0FXZWJQcm90b2J1Zn'
    'NXZWIuUGluSW5DaGF0UglwaW5JbkNoYXQSVQoScHJlbWl1bU1lc3NhZ2VJbmZvGDcgASgLMiUu'
    'V0FXZWJQcm90b2J1ZnNXZWIuUHJlbWl1bU1lc3NhZ2VJbmZvUhJwcmVtaXVtTWVzc2FnZUluZm'
    '8SLAoRaXMxUEJpekJvdE1lc3NhZ2UYOCABKAhSEWlzMVBCaXpCb3RNZXNzYWdlEjQKFWlzR3Jv'
    'dXBIaXN0b3J5TWVzc2FnZRg5IAEoCFIVaXNHcm91cEhpc3RvcnlNZXNzYWdlEjIKFGJvdE1lc3'
    'NhZ2VJbnZva2VySklEGDogASgJUhRib3RNZXNzYWdlSW52b2tlckpJRBJMCg9jb21tZW50TWV0'
    'YWRhdGEYOyABKAsyIi5XQVdlYlByb3RvYnVmc1dlYi5Db21tZW50TWV0YWRhdGFSD2NvbW1lbn'
    'RNZXRhZGF0YRJICg5ldmVudFJlc3BvbnNlcxg9IAMoCzIgLldBV2ViUHJvdG9idWZzV2ViLkV2'
    'ZW50UmVzcG9uc2VSDmV2ZW50UmVzcG9uc2VzElUKEnJlcG9ydGluZ1Rva2VuSW5mbxg+IAEoCz'
    'IlLldBV2ViUHJvdG9idWZzV2ViLlJlcG9ydGluZ1Rva2VuSW5mb1IScmVwb3J0aW5nVG9rZW5J'
    'bmZvEi4KEm5ld3NsZXR0ZXJTZXJ2ZXJJRBg/IAEoBFISbmV3c2xldHRlclNlcnZlcklEEmQKF2'
    'V2ZW50QWRkaXRpb25hbE1ldGFkYXRhGEAgASgLMiouV0FXZWJQcm90b2J1ZnNXZWIuRXZlbnRB'
    'ZGRpdGlvbmFsTWV0YWRhdGFSF2V2ZW50QWRkaXRpb25hbE1ldGFkYXRhEjAKE2lzTWVudGlvbm'
    'VkSW5TdGF0dXMYQSABKAhSE2lzTWVudGlvbmVkSW5TdGF0dXMSJgoOc3RhdHVzTWVudGlvbnMY'
    'QiADKAlSDnN0YXR1c01lbnRpb25zEj4KD3RhcmdldE1lc3NhZ2VJRBhDIAEoCzIULldBQ29tbW'
    '9uLk1lc3NhZ2VLZXlSD3RhcmdldE1lc3NhZ2VJRBJFCg1tZXNzYWdlQWRkT25zGEQgAygLMh8u'
    'V0FXZWJQcm90b2J1ZnNXZWIuTWVzc2FnZUFkZE9uUg1tZXNzYWdlQWRkT25zEmMKGHN0YXR1c0'
    '1lbnRpb25NZXNzYWdlSW5mbxhFIAEoCzInLldBV2ViUHJvdG9idWZzV2ViLlN0YXR1c01lbnRp'
    'b25NZXNzYWdlUhhzdGF0dXNNZW50aW9uTWVzc2FnZUluZm8SLgoSaXNTdXBwb3J0QWlNZXNzYW'
    'dlGEYgASgIUhJpc1N1cHBvcnRBaU1lc3NhZ2USMgoUc3RhdHVzTWVudGlvblNvdXJjZXMYRyAD'
    'KAlSFHN0YXR1c01lbnRpb25Tb3VyY2VzEksKEnN1cHBvcnRBaUNpdGF0aW9ucxhIIAMoCzIbLl'
    'dBV2ViUHJvdG9idWZzV2ViLkNpdGF0aW9uUhJzdXBwb3J0QWlDaXRhdGlvbnMSIAoLYm90VGFy'
    'Z2V0SUQYSSABKAlSC2JvdFRhcmdldElEIj0KEEJpelByaXZhY3lTdGF0dXMSCAoERTJFRRAAEg'
    'YKAkZCEAISBwoDQlNQEAESDgoKQlNQX0FORF9GQhADIu85CghTdHViVHlwZRILCgdVTktOT1dO'
    'EAASCgoGUkVWT0tFEAESDgoKQ0lQSEVSVEVYVBACEg8KC0ZVVFVSRVBST09GEAMSGwoXTk9OX1'
    'ZFUklGSUVEX1RSQU5TSVRJT04QBBIZChVVTlZFUklGSUVEX1RSQU5TSVRJT04QBRIXChNWRVJJ'
    'RklFRF9UUkFOU0lUSU9OEAYSGAoUVkVSSUZJRURfTE9XX1VOS05PV04QBxIRCg1WRVJJRklFRF'
    '9ISUdIEAgSHAoYVkVSSUZJRURfSU5JVElBTF9VTktOT1dOEAkSGAoUVkVSSUZJRURfSU5JVElB'
    'TF9MT1cQChIZChVWRVJJRklFRF9JTklUSUFMX0hJR0gQCxIjCh9WRVJJRklFRF9UUkFOU0lUSU'
    '9OX0FOWV9UT19OT05FEAwSIwofVkVSSUZJRURfVFJBTlNJVElPTl9BTllfVE9fSElHSBANEiMK'
    'H1ZFUklGSUVEX1RSQU5TSVRJT05fSElHSF9UT19MT1cQDhInCiNWRVJJRklFRF9UUkFOU0lUSU'
    '9OX0hJR0hfVE9fVU5LTk9XThAPEiYKIlZFUklGSUVEX1RSQU5TSVRJT05fVU5LTk9XTl9UT19M'
    'T1cQEBImCiJWRVJJRklFRF9UUkFOU0lUSU9OX0xPV19UT19VTktOT1dOEBESIwofVkVSSUZJRU'
    'RfVFJBTlNJVElPTl9OT05FX1RPX0xPVxASEicKI1ZFUklGSUVEX1RSQU5TSVRJT05fTk9ORV9U'
    'T19VTktOT1dOEBMSEAoMR1JPVVBfQ1JFQVRFEBQSGAoUR1JPVVBfQ0hBTkdFX1NVQkpFQ1QQFR'
    'IVChFHUk9VUF9DSEFOR0VfSUNPThAWEhwKGEdST1VQX0NIQU5HRV9JTlZJVEVfTElOSxAXEhwK'
    'GEdST1VQX0NIQU5HRV9ERVNDUklQVElPThAYEhkKFUdST1VQX0NIQU5HRV9SRVNUUklDVBAZEh'
    'kKFUdST1VQX0NIQU5HRV9BTk5PVU5DRRAaEhkKFUdST1VQX1BBUlRJQ0lQQU5UX0FERBAbEhwK'
    'GEdST1VQX1BBUlRJQ0lQQU5UX1JFTU9WRRAcEh0KGUdST1VQX1BBUlRJQ0lQQU5UX1BST01PVE'
    'UQHRIcChhHUk9VUF9QQVJUSUNJUEFOVF9ERU1PVEUQHhIcChhHUk9VUF9QQVJUSUNJUEFOVF9J'
    'TlZJVEUQHxIbChdHUk9VUF9QQVJUSUNJUEFOVF9MRUFWRRAgEiMKH0dST1VQX1BBUlRJQ0lQQU'
    '5UX0NIQU5HRV9OVU1CRVIQIRIUChBCUk9BRENBU1RfQ1JFQVRFECISEQoNQlJPQURDQVNUX0FE'
    'RBAjEhQKEEJST0FEQ0FTVF9SRU1PVkUQJBIYChRHRU5FUklDX05PVElGSUNBVElPThAlEhgKFE'
    'UyRV9JREVOVElUWV9DSEFOR0VEECYSEQoNRTJFX0VOQ1JZUFRFRBAnEhUKEUNBTExfTUlTU0VE'
    'X1ZPSUNFECgSFQoRQ0FMTF9NSVNTRURfVklERU8QKRIcChhJTkRJVklEVUFMX0NIQU5HRV9OVU'
    '1CRVIQKhIQCgxHUk9VUF9ERUxFVEUQKxImCiJHUk9VUF9BTk5PVU5DRV9NT0RFX01FU1NBR0Vf'
    'Qk9VTkNFECwSGwoXQ0FMTF9NSVNTRURfR1JPVVBfVk9JQ0UQLRIbChdDQUxMX01JU1NFRF9HUk'
    '9VUF9WSURFTxAuEhYKElBBWU1FTlRfQ0lQSEVSVEVYVBAvEhcKE1BBWU1FTlRfRlVUVVJFUFJP'
    'T0YQMBIsCihQQVlNRU5UX1RSQU5TQUNUSU9OX1NUQVRVU19VUERBVEVfRkFJTEVEEDESLgoqUE'
    'FZTUVOVF9UUkFOU0FDVElPTl9TVEFUVVNfVVBEQVRFX1JFRlVOREVEEDISMwovUEFZTUVOVF9U'
    'UkFOU0FDVElPTl9TVEFUVVNfVVBEQVRFX1JFRlVORF9GQUlMRUQQMxI1CjFQQVlNRU5UX1RSQU'
    '5TQUNUSU9OX1NUQVRVU19SRUNFSVZFUl9QRU5ESU5HX1NFVFVQEDQSPAo4UEFZTUVOVF9UUkFO'
    'U0FDVElPTl9TVEFUVVNfUkVDRUlWRVJfU1VDQ0VTU19BRlRFUl9ISUNDVVAQNRIpCiVQQVlNRU'
    '5UX0FDVElPTl9BQ0NPVU5UX1NFVFVQX1JFTUlOREVSEDYSKAokUEFZTUVOVF9BQ1RJT05fU0VO'
    'RF9QQVlNRU5UX1JFTUlOREVSEDcSKgomUEFZTUVOVF9BQ1RJT05fU0VORF9QQVlNRU5UX0lOVk'
    'lUQVRJT04QOBIjCh9QQVlNRU5UX0FDVElPTl9SRVFVRVNUX0RFQ0xJTkVEEDkSIgoeUEFZTUVO'
    'VF9BQ1RJT05fUkVRVUVTVF9FWFBJUkVEEDoSJAogUEFZTUVOVF9BQ1RJT05fUkVRVUVTVF9DQU'
    '5DRUxMRUQQOxIpCiVCSVpfVkVSSUZJRURfVFJBTlNJVElPTl9UT1BfVE9fQk9UVE9NEDwSKQol'
    'QklaX1ZFUklGSUVEX1RSQU5TSVRJT05fQk9UVE9NX1RPX1RPUBA9EhEKDUJJWl9JTlRST19UT1'
    'AQPhIUChBCSVpfSU5UUk9fQk9UVE9NED8SEwoPQklaX05BTUVfQ0hBTkdFEEASHAoYQklaX01P'
    'VkVfVE9fQ09OU1VNRVJfQVBQEEESHgoaQklaX1RXT19USUVSX01JR1JBVElPTl9UT1AQQhIhCh'
    '1CSVpfVFdPX1RJRVJfTUlHUkFUSU9OX0JPVFRPTRBDEg0KCU9WRVJTSVpFRBBEEigKJEdST1VQ'
    'X0NIQU5HRV9OT19GUkVRVUVOVExZX0ZPUldBUkRFRBBFEhwKGEdST1VQX1Y0X0FERF9JTlZJVE'
    'VfU0VOVBBGEiYKIkdST1VQX1BBUlRJQ0lQQU5UX0FERF9SRVFVRVNUX0pPSU4QRxIcChhDSEFO'
    'R0VfRVBIRU1FUkFMX1NFVFRJTkcQSBIWChJFMkVfREVWSUNFX0NIQU5HRUQQSRIPCgtWSUVXRU'
    'RfT05DRRBKEhUKEUUyRV9FTkNSWVBURURfTk9XEEsSIgoeQkxVRV9NU0dfQlNQX0ZCX1RPX0JT'
    'UF9QUkVNSVNFEEwSHgoaQkxVRV9NU0dfQlNQX0ZCX1RPX1NFTEZfRkIQTRIjCh9CTFVFX01TR1'
    '9CU1BfRkJfVE9fU0VMRl9QUkVNSVNFEE4SHgoaQkxVRV9NU0dfQlNQX0ZCX1VOVkVSSUZJRUQQ'
    'TxI3CjNCTFVFX01TR19CU1BfRkJfVU5WRVJJRklFRF9UT19TRUxGX1BSRU1JU0VfVkVSSUZJRU'
    'QQUBIcChhCTFVFX01TR19CU1BfRkJfVkVSSUZJRUQQURI3CjNCTFVFX01TR19CU1BfRkJfVkVS'
    'SUZJRURfVE9fU0VMRl9QUkVNSVNFX1VOVkVSSUZJRUQQUhIoCiRCTFVFX01TR19CU1BfUFJFTU'
    'lTRV9UT19TRUxGX1BSRU1JU0UQUxIjCh9CTFVFX01TR19CU1BfUFJFTUlTRV9VTlZFUklGSUVE'
    'EFQSPAo4QkxVRV9NU0dfQlNQX1BSRU1JU0VfVU5WRVJJRklFRF9UT19TRUxGX1BSRU1JU0VfVk'
    'VSSUZJRUQQVRIhCh1CTFVFX01TR19CU1BfUFJFTUlTRV9WRVJJRklFRBBWEjwKOEJMVUVfTVNH'
    'X0JTUF9QUkVNSVNFX1ZFUklGSUVEX1RPX1NFTEZfUFJFTUlTRV9VTlZFUklGSUVEEFcSKgomQk'
    'xVRV9NU0dfQ09OU1VNRVJfVE9fQlNQX0ZCX1VOVkVSSUZJRUQQWBIvCitCTFVFX01TR19DT05T'
    'VU1FUl9UT19CU1BfUFJFTUlTRV9VTlZFUklGSUVEEFkSKwonQkxVRV9NU0dfQ09OU1VNRVJfVE'
    '9fU0VMRl9GQl9VTlZFUklGSUVEEFoSMAosQkxVRV9NU0dfQ09OU1VNRVJfVE9fU0VMRl9QUkVN'
    'SVNFX1VOVkVSSUZJRUQQWxIjCh9CTFVFX01TR19TRUxGX0ZCX1RPX0JTUF9QUkVNSVNFEFwSJA'
    'ogQkxVRV9NU0dfU0VMRl9GQl9UT19TRUxGX1BSRU1JU0UQXRIfChtCTFVFX01TR19TRUxGX0ZC'
    'X1VOVkVSSUZJRUQQXhI4CjRCTFVFX01TR19TRUxGX0ZCX1VOVkVSSUZJRURfVE9fU0VMRl9QUk'
    'VNSVNFX1ZFUklGSUVEEF8SHQoZQkxVRV9NU0dfU0VMRl9GQl9WRVJJRklFRBBgEjgKNEJMVUVf'
    'TVNHX1NFTEZfRkJfVkVSSUZJRURfVE9fU0VMRl9QUkVNSVNFX1VOVkVSSUZJRUQQYRIoCiRCTF'
    'VFX01TR19TRUxGX1BSRU1JU0VfVE9fQlNQX1BSRU1JU0UQYhIkCiBCTFVFX01TR19TRUxGX1BS'
    'RU1JU0VfVU5WRVJJRklFRBBjEiIKHkJMVUVfTVNHX1NFTEZfUFJFTUlTRV9WRVJJRklFRBBkEh'
    'YKEkJMVUVfTVNHX1RPX0JTUF9GQhBlEhgKFEJMVUVfTVNHX1RPX0NPTlNVTUVSEGYSFwoTQkxV'
    'RV9NU0dfVE9fU0VMRl9GQhBnEioKJkJMVUVfTVNHX1VOVkVSSUZJRURfVE9fQlNQX0ZCX1ZFUk'
    'lGSUVEEGgSLworQkxVRV9NU0dfVU5WRVJJRklFRF9UT19CU1BfUFJFTUlTRV9WRVJJRklFRBBp'
    'EisKJ0JMVUVfTVNHX1VOVkVSSUZJRURfVE9fU0VMRl9GQl9WRVJJRklFRBBqEiMKH0JMVUVfTV'
    'NHX1VOVkVSSUZJRURfVE9fVkVSSUZJRUQQaxIqCiZCTFVFX01TR19WRVJJRklFRF9UT19CU1Bf'
    'RkJfVU5WRVJJRklFRBBsEi8KK0JMVUVfTVNHX1ZFUklGSUVEX1RPX0JTUF9QUkVNSVNFX1VOVk'
    'VSSUZJRUQQbRIrCidCTFVFX01TR19WRVJJRklFRF9UT19TRUxGX0ZCX1VOVkVSSUZJRUQQbhIj'
    'Ch9CTFVFX01TR19WRVJJRklFRF9UT19VTlZFUklGSUVEEG8SNgoyQkxVRV9NU0dfQlNQX0ZCX1'
    'VOVkVSSUZJRURfVE9fQlNQX1BSRU1JU0VfVkVSSUZJRUQQcBIyCi5CTFVFX01TR19CU1BfRkJf'
    'VU5WRVJJRklFRF9UT19TRUxGX0ZCX1ZFUklGSUVEEHESNgoyQkxVRV9NU0dfQlNQX0ZCX1ZFUk'
    'lGSUVEX1RPX0JTUF9QUkVNSVNFX1VOVkVSSUZJRUQQchIyCi5CTFVFX01TR19CU1BfRkJfVkVS'
    'SUZJRURfVE9fU0VMRl9GQl9VTlZFUklGSUVEEHMSNwozQkxVRV9NU0dfU0VMRl9GQl9VTlZFUk'
    'lGSUVEX1RPX0JTUF9QUkVNSVNFX1ZFUklGSUVEEHQSNwozQkxVRV9NU0dfU0VMRl9GQl9WRVJJ'
    'RklFRF9UT19CU1BfUFJFTUlTRV9VTlZFUklGSUVEEHUSHAoYRTJFX0lERU5USVRZX1VOQVZBSU'
    'xBQkxFEHYSEgoOR1JPVVBfQ1JFQVRJTkcQdxIXChNHUk9VUF9DUkVBVEVfRkFJTEVEEHgSEQoN'
    'R1JPVVBfQk9VTkNFRBB5EhEKDUJMT0NLX0NPTlRBQ1QQehIhCh1FUEhFTUVSQUxfU0VUVElOR1'
    '9OT1RfQVBQTElFRBB7Eg8KC1NZTkNfRkFJTEVEEHwSCwoHU1lOQ0lORxB9EhwKGEJJWl9QUklW'
    'QUNZX01PREVfSU5JVF9GQhB+Eh0KGUJJWl9QUklWQUNZX01PREVfSU5JVF9CU1AQfxIbChZCSV'
    'pfUFJJVkFDWV9NT0RFX1RPX0ZCEIABEhwKF0JJWl9QUklWQUNZX01PREVfVE9fQlNQEIEBEhYK'
    'EURJU0FQUEVBUklOR19NT0RFEIIBEhwKF0UyRV9ERVZJQ0VfRkVUQ0hfRkFJTEVEEIMBEhEKDE'
    'FETUlOX1JFVk9LRRCEARIkCh9HUk9VUF9JTlZJVEVfTElOS19HUk9XVEhfTE9DS0VEEIUBEiAK'
    'G0NPTU1VTklUWV9MSU5LX1BBUkVOVF9HUk9VUBCGARIhChxDT01NVU5JVFlfTElOS19TSUJMSU'
    '5HX0dST1VQEIcBEh0KGENPTU1VTklUWV9MSU5LX1NVQl9HUk9VUBCIARIiCh1DT01NVU5JVFlf'
    'VU5MSU5LX1BBUkVOVF9HUk9VUBCJARIjCh5DT01NVU5JVFlfVU5MSU5LX1NJQkxJTkdfR1JPVV'
    'AQigESHwoaQ09NTVVOSVRZX1VOTElOS19TVUJfR1JPVVAQiwESHQoYR1JPVVBfUEFSVElDSVBB'
    'TlRfQUNDRVBUEIwBEigKI0dST1VQX1BBUlRJQ0lQQU5UX0xJTktFRF9HUk9VUF9KT0lOEI0BEh'
    'UKEENPTU1VTklUWV9DUkVBVEUQjgESGwoWRVBIRU1FUkFMX0tFRVBfSU5fQ0hBVBCPARIrCiZH'
    'Uk9VUF9NRU1CRVJTSElQX0pPSU5fQVBQUk9WQUxfUkVRVUVTVBCQARIoCiNHUk9VUF9NRU1CRV'
    'JTSElQX0pPSU5fQVBQUk9WQUxfTU9ERRCRARIiCh1JTlRFR1JJVFlfVU5MSU5LX1BBUkVOVF9H'
    'Uk9VUBCSARIiCh1DT01NVU5JVFlfUEFSVElDSVBBTlRfUFJPTU9URRCTARIhChxDT01NVU5JVF'
    'lfUEFSVElDSVBBTlRfREVNT1RFEJQBEiMKHkNPTU1VTklUWV9QQVJFTlRfR1JPVVBfREVMRVRF'
    'RBCVARI0Ci9DT01NVU5JVFlfTElOS19QQVJFTlRfR1JPVVBfTUVNQkVSU0hJUF9BUFBST1ZBTB'
    'CWARI0Ci9HUk9VUF9QQVJUSUNJUEFOVF9KT0lORURfR1JPVVBfQU5EX1BBUkVOVF9HUk9VUBCX'
    'ARIaChVNQVNLRURfVEhSRUFEX0NSRUFURUQQmAESGwoWTUFTS0VEX1RIUkVBRF9VTk1BU0tFRB'
    'CZARIYChNCSVpfQ0hBVF9BU1NJR05NRU5UEJoBEg0KCENIQVRfUFNBEJsBEh8KGkNIQVRfUE9M'
    'TF9DUkVBVElPTl9NRVNTQUdFEJwBEh4KGUNBR19NQVNLRURfVEhSRUFEX0NSRUFURUQQnQESKw'
    'omQ09NTVVOSVRZX1BBUkVOVF9HUk9VUF9TVUJKRUNUX0NIQU5HRUQQngESGAoTQ0FHX0lOVklU'
    'RV9BVVRPX0FERBCfARIhChxCSVpfQ0hBVF9BU1NJR05NRU5UX1VOQVNTSUdOEKABEhsKFkNBR1'
    '9JTlZJVEVfQVVUT19KT0lORUQQoQESIQocU0NIRURVTEVEX0NBTExfU1RBUlRfTUVTU0FHRRCi'
    'ARIaChVDT01NVU5JVFlfSU5WSVRFX1JJQ0gQowESIwoeQ09NTVVOSVRZX0lOVklURV9BVVRPX0'
    'FERF9SSUNIEKQBEhoKFVNVQl9HUk9VUF9JTlZJVEVfUklDSBClARIjCh5TVUJfR1JPVVBfUEFS'
    'VElDSVBBTlRfQUREX1JJQ0gQpgESJQogQ09NTVVOSVRZX0xJTktfUEFSRU5UX0dST1VQX1JJQ0'
    'gQpwESIwoeQ09NTVVOSVRZX1BBUlRJQ0lQQU5UX0FERF9SSUNIEKgBEiIKHVNJTEVOQ0VEX1VO'
    'S05PV05fQ0FMTEVSX0FVRElPEKkBEiIKHVNJTEVOQ0VEX1VOS05PV05fQ0FMTEVSX1ZJREVPEK'
    'oBEhoKFUdST1VQX01FTUJFUl9BRERfTU9ERRCrARI5CjRHUk9VUF9NRU1CRVJTSElQX0pPSU5f'
    'QVBQUk9WQUxfUkVRVUVTVF9OT05fQURNSU5fQUREEKwBEiEKHENPTU1VTklUWV9DSEFOR0VfRE'
    'VTQ1JJUFRJT04QrQESEgoNU0VOREVSX0lOVklURRCuARIUCg9SRUNFSVZFUl9JTlZJVEUQrwES'
    'KAojQ09NTVVOSVRZX0FMTE9XX01FTUJFUl9BRERFRF9HUk9VUFMQsAESGwoWUElOTkVEX01FU1'
    'NBR0VfSU5fQ0hBVBCxARIhChxQQVlNRU5UX0lOVklURV9TRVRVUF9JTlZJVEVSELIBEi4KKVBB'
    'WU1FTlRfSU5WSVRFX1NFVFVQX0lOVklURUVfUkVDRUlWRV9PTkxZELMBEjIKLVBBWU1FTlRfSU'
    '5WSVRFX1NFVFVQX0lOVklURUVfU0VORF9BTkRfUkVDRUlWRRC0ARIcChdMSU5LRURfR1JPVVBf'
    'Q0FMTF9TVEFSVBC1ARIjCh5SRVBPUlRfVE9fQURNSU5fRU5BQkxFRF9TVEFUVVMQtgESGgoVRU'
    '1QVFlfU1VCR1JPVVBfQ1JFQVRFELcBEhoKFVNDSEVEVUxFRF9DQUxMX0NBTkNFTBC4ARIrCiZT'
    'VUJHUk9VUF9BRE1JTl9UUklHR0VSRURfQVVUT19BRERfUklDSBC5ARIoCiNHUk9VUF9DSEFOR0'
    'VfUkVDRU5UX0hJU1RPUllfU0hBUklORxC6ARIkCh9QQUlEX01FU1NBR0VfU0VSVkVSX0NBTVBB'
    'SUdOX0lEELsBEhgKE0dFTkVSQUxfQ0hBVF9DUkVBVEUQvAESFQoQR0VORVJBTF9DSEFUX0FERB'
    'C9ARIjCh5HRU5FUkFMX0NIQVRfQVVUT19BRERfRElTQUJMRUQQvgESIAobU1VHR0VTVEVEX1NV'
    'QkdST1VQX0FOTk9VTkNFEL8BEiEKHEJJWl9CT1RfMVBfTUVTU0FHSU5HX0VOQUJMRUQQwAESFA'
    'oPQ0hBTkdFX1VTRVJOQU1FEMEBEh8KGkJJWl9DT0VYX1BSSVZBQ1lfSU5JVF9TRUxGEMIBEiUK'
    'IEJJWl9DT0VYX1BSSVZBQ1lfVFJBTlNJVElPTl9TRUxGEMMBEhkKFFNVUFBPUlRfQUlfRURVQ0'
    'FUSU9OEMQBEiEKHEJJWl9CT1RfM1BfTUVTU0FHSU5HX0VOQUJMRUQQxQESGwoWUkVNSU5ERVJf'
    'U0VUVVBfTUVTU0FHRRDGARIaChVSRU1JTkRFUl9TRU5UX01FU1NBR0UQxwESHAoXUkVNSU5ERV'
    'JfQ0FOQ0VMX01FU1NBR0UQyAESGgoVQklaX0NPRVhfUFJJVkFDWV9JTklUEMkBEiAKG0JJWl9D'
    'T0VYX1BSSVZBQ1lfVFJBTlNJVElPThDKARIWChFHUk9VUF9ERUFDVElWQVRFRBDLARInCiJDT0'
    '1NVU5JVFlfREVBQ1RJVkFURV9TSUJMSU5HX0dST1VQEMwBEhIKDUVWRU5UX1VQREFURUQQzQES'
    'EwoORVZFTlRfQ0FOQ0VMRUQQzgESHAoXQ09NTVVOSVRZX09XTkVSX1VQREFURUQQzwESKgolQ0'
    '9NTVVOSVRZX1NVQl9HUk9VUF9WSVNJQklMSVRZX0hJRERFThDQARIkCh9DQVBJX0dST1VQX05F'
    'MkVFX1NZU1RFTV9NRVNTQUdFENEBEhMKDlNUQVRVU19NRU5USU9OENIBEiEKHFVTRVJfQ09OVF'
    'JPTFNfU1lTVEVNX01FU1NBR0UQ0wESGwoWU1VQUE9SVF9TWVNURU1fTUVTU0FHRRDUARIPCgpD'
    'SEFOR0VfTElEENUBEjEKLEJJWl9DVVNUT01FUl8zUERfREFUQV9TSEFSSU5HX09QVF9JTl9NRV'
    'NTQUdFENYBEjIKLUJJWl9DVVNUT01FUl8zUERfREFUQV9TSEFSSU5HX09QVF9PVVRfTUVTU0FH'
    'RRDXARIZChRDSEFOR0VfTElNSVRfU0hBUklORxDYARIbChZHUk9VUF9NRU1CRVJfTElOS19NT0'
    'RFENkBIlgKBlN0YXR1cxIJCgVFUlJPUhAAEgsKB1BFTkRJTkcQARIOCgpTRVJWRVJfQUNLEAIS'
    'EAoMREVMSVZFUllfQUNLEAMSCAoEUkVBRBAEEgoKBlBMQVlFRBAF');

@$core.Deprecated('Use paymentInfoDescriptor instead')
const PaymentInfo$json = {
  '1': 'PaymentInfo',
  '2': [
    {'1': 'currencyDeprecated', '3': 1, '4': 1, '5': 14, '6': '.WAWebProtobufsWeb.PaymentInfo.Currency', '10': 'currencyDeprecated'},
    {'1': 'amount1000', '3': 2, '4': 1, '5': 4, '10': 'amount1000'},
    {'1': 'receiverJID', '3': 3, '4': 1, '5': 9, '10': 'receiverJID'},
    {'1': 'status', '3': 4, '4': 1, '5': 14, '6': '.WAWebProtobufsWeb.PaymentInfo.Status', '10': 'status'},
    {'1': 'transactionTimestamp', '3': 5, '4': 1, '5': 4, '10': 'transactionTimestamp'},
    {'1': 'requestMessageKey', '3': 6, '4': 1, '5': 11, '6': '.WACommon.MessageKey', '10': 'requestMessageKey'},
    {'1': 'expiryTimestamp', '3': 7, '4': 1, '5': 4, '10': 'expiryTimestamp'},
    {'1': 'futureproofed', '3': 8, '4': 1, '5': 8, '10': 'futureproofed'},
    {'1': 'currency', '3': 9, '4': 1, '5': 9, '10': 'currency'},
    {'1': 'txnStatus', '3': 10, '4': 1, '5': 14, '6': '.WAWebProtobufsWeb.PaymentInfo.TxnStatus', '10': 'txnStatus'},
    {'1': 'useNoviFiatFormat', '3': 11, '4': 1, '5': 8, '10': 'useNoviFiatFormat'},
    {'1': 'primaryAmount', '3': 12, '4': 1, '5': 11, '6': '.WAWebProtobufsE2E.Money', '10': 'primaryAmount'},
    {'1': 'exchangeAmount', '3': 13, '4': 1, '5': 11, '6': '.WAWebProtobufsE2E.Money', '10': 'exchangeAmount'},
  ],
  '4': [PaymentInfo_TxnStatus$json, PaymentInfo_Status$json, PaymentInfo_Currency$json],
};

@$core.Deprecated('Use paymentInfoDescriptor instead')
const PaymentInfo_TxnStatus$json = {
  '1': 'TxnStatus',
  '2': [
    {'1': 'UNKNOWN', '2': 0},
    {'1': 'PENDING_SETUP', '2': 1},
    {'1': 'PENDING_RECEIVER_SETUP', '2': 2},
    {'1': 'INIT', '2': 3},
    {'1': 'SUCCESS', '2': 4},
    {'1': 'COMPLETED', '2': 5},
    {'1': 'FAILED', '2': 6},
    {'1': 'FAILED_RISK', '2': 7},
    {'1': 'FAILED_PROCESSING', '2': 8},
    {'1': 'FAILED_RECEIVER_PROCESSING', '2': 9},
    {'1': 'FAILED_DA', '2': 10},
    {'1': 'FAILED_DA_FINAL', '2': 11},
    {'1': 'REFUNDED_TXN', '2': 12},
    {'1': 'REFUND_FAILED', '2': 13},
    {'1': 'REFUND_FAILED_PROCESSING', '2': 14},
    {'1': 'REFUND_FAILED_DA', '2': 15},
    {'1': 'EXPIRED_TXN', '2': 16},
    {'1': 'AUTH_CANCELED', '2': 17},
    {'1': 'AUTH_CANCEL_FAILED_PROCESSING', '2': 18},
    {'1': 'AUTH_CANCEL_FAILED', '2': 19},
    {'1': 'COLLECT_INIT', '2': 20},
    {'1': 'COLLECT_SUCCESS', '2': 21},
    {'1': 'COLLECT_FAILED', '2': 22},
    {'1': 'COLLECT_FAILED_RISK', '2': 23},
    {'1': 'COLLECT_REJECTED', '2': 24},
    {'1': 'COLLECT_EXPIRED', '2': 25},
    {'1': 'COLLECT_CANCELED', '2': 26},
    {'1': 'COLLECT_CANCELLING', '2': 27},
    {'1': 'IN_REVIEW', '2': 28},
    {'1': 'REVERSAL_SUCCESS', '2': 29},
    {'1': 'REVERSAL_PENDING', '2': 30},
    {'1': 'REFUND_PENDING', '2': 31},
  ],
};

@$core.Deprecated('Use paymentInfoDescriptor instead')
const PaymentInfo_Status$json = {
  '1': 'Status',
  '2': [
    {'1': 'UNKNOWN_STATUS', '2': 0},
    {'1': 'PROCESSING', '2': 1},
    {'1': 'SENT', '2': 2},
    {'1': 'NEED_TO_ACCEPT', '2': 3},
    {'1': 'COMPLETE', '2': 4},
    {'1': 'COULD_NOT_COMPLETE', '2': 5},
    {'1': 'REFUNDED', '2': 6},
    {'1': 'EXPIRED', '2': 7},
    {'1': 'REJECTED', '2': 8},
    {'1': 'CANCELLED', '2': 9},
    {'1': 'WAITING_FOR_PAYER', '2': 10},
    {'1': 'WAITING', '2': 11},
  ],
};

@$core.Deprecated('Use paymentInfoDescriptor instead')
const PaymentInfo_Currency$json = {
  '1': 'Currency',
  '2': [
    {'1': 'UNKNOWN_CURRENCY', '2': 0},
    {'1': 'INR', '2': 1},
  ],
};

/// Descriptor for `PaymentInfo`. Decode as a `google.protobuf.DescriptorProto`.
final $typed_data.Uint8List paymentInfoDescriptor = $convert.base64Decode(
    'CgtQYXltZW50SW5mbxJXChJjdXJyZW5jeURlcHJlY2F0ZWQYASABKA4yJy5XQVdlYlByb3RvYn'
    'Vmc1dlYi5QYXltZW50SW5mby5DdXJyZW5jeVISY3VycmVuY3lEZXByZWNhdGVkEh4KCmFtb3Vu'
    'dDEwMDAYAiABKARSCmFtb3VudDEwMDASIAoLcmVjZWl2ZXJKSUQYAyABKAlSC3JlY2VpdmVySk'
    'lEEj0KBnN0YXR1cxgEIAEoDjIlLldBV2ViUHJvdG9idWZzV2ViLlBheW1lbnRJbmZvLlN0YXR1'
    'c1IGc3RhdHVzEjIKFHRyYW5zYWN0aW9uVGltZXN0YW1wGAUgASgEUhR0cmFuc2FjdGlvblRpbW'
    'VzdGFtcBJCChFyZXF1ZXN0TWVzc2FnZUtleRgGIAEoCzIULldBQ29tbW9uLk1lc3NhZ2VLZXlS'
    'EXJlcXVlc3RNZXNzYWdlS2V5EigKD2V4cGlyeVRpbWVzdGFtcBgHIAEoBFIPZXhwaXJ5VGltZX'
    'N0YW1wEiQKDWZ1dHVyZXByb29mZWQYCCABKAhSDWZ1dHVyZXByb29mZWQSGgoIY3VycmVuY3kY'
    'CSABKAlSCGN1cnJlbmN5EkYKCXR4blN0YXR1cxgKIAEoDjIoLldBV2ViUHJvdG9idWZzV2ViLl'
    'BheW1lbnRJbmZvLlR4blN0YXR1c1IJdHhuU3RhdHVzEiwKEXVzZU5vdmlGaWF0Rm9ybWF0GAsg'
    'ASgIUhF1c2VOb3ZpRmlhdEZvcm1hdBI+Cg1wcmltYXJ5QW1vdW50GAwgASgLMhguV0FXZWJQcm'
    '90b2J1ZnNFMkUuTW9uZXlSDXByaW1hcnlBbW91bnQSQAoOZXhjaGFuZ2VBbW91bnQYDSABKAsy'
    'GC5XQVdlYlByb3RvYnVmc0UyRS5Nb25leVIOZXhjaGFuZ2VBbW91bnQimQUKCVR4blN0YXR1cx'
    'ILCgdVTktOT1dOEAASEQoNUEVORElOR19TRVRVUBABEhoKFlBFTkRJTkdfUkVDRUlWRVJfU0VU'
    'VVAQAhIICgRJTklUEAMSCwoHU1VDQ0VTUxAEEg0KCUNPTVBMRVRFRBAFEgoKBkZBSUxFRBAGEg'
    '8KC0ZBSUxFRF9SSVNLEAcSFQoRRkFJTEVEX1BST0NFU1NJTkcQCBIeChpGQUlMRURfUkVDRUlW'
    'RVJfUFJPQ0VTU0lORxAJEg0KCUZBSUxFRF9EQRAKEhMKD0ZBSUxFRF9EQV9GSU5BTBALEhAKDF'
    'JFRlVOREVEX1RYThAMEhEKDVJFRlVORF9GQUlMRUQQDRIcChhSRUZVTkRfRkFJTEVEX1BST0NF'
    'U1NJTkcQDhIUChBSRUZVTkRfRkFJTEVEX0RBEA8SDwoLRVhQSVJFRF9UWE4QEBIRCg1BVVRIX0'
    'NBTkNFTEVEEBESIQodQVVUSF9DQU5DRUxfRkFJTEVEX1BST0NFU1NJTkcQEhIWChJBVVRIX0NB'
    'TkNFTF9GQUlMRUQQExIQCgxDT0xMRUNUX0lOSVQQFBITCg9DT0xMRUNUX1NVQ0NFU1MQFRISCg'
    '5DT0xMRUNUX0ZBSUxFRBAWEhcKE0NPTExFQ1RfRkFJTEVEX1JJU0sQFxIUChBDT0xMRUNUX1JF'
    'SkVDVEVEEBgSEwoPQ09MTEVDVF9FWFBJUkVEEBkSFAoQQ09MTEVDVF9DQU5DRUxFRBAaEhYKEk'
    'NPTExFQ1RfQ0FOQ0VMTElORxAbEg0KCUlOX1JFVklFVxAcEhQKEFJFVkVSU0FMX1NVQ0NFU1MQ'
    'HRIUChBSRVZFUlNBTF9QRU5ESU5HEB4SEgoOUkVGVU5EX1BFTkRJTkcQHyLMAQoGU3RhdHVzEh'
    'IKDlVOS05PV05fU1RBVFVTEAASDgoKUFJPQ0VTU0lORxABEggKBFNFTlQQAhISCg5ORUVEX1RP'
    'X0FDQ0VQVBADEgwKCENPTVBMRVRFEAQSFgoSQ09VTERfTk9UX0NPTVBMRVRFEAUSDAoIUkVGVU'
    '5ERUQQBhILCgdFWFBJUkVEEAcSDAoIUkVKRUNURUQQCBINCglDQU5DRUxMRUQQCRIVChFXQUlU'
    'SU5HX0ZPUl9QQVlFUhAKEgsKB1dBSVRJTkcQCyIpCghDdXJyZW5jeRIUChBVTktOT1dOX0NVUl'
    'JFTkNZEAASBwoDSU5SEAE=');

@$core.Deprecated('Use webFeaturesDescriptor instead')
const WebFeatures$json = {
  '1': 'WebFeatures',
  '2': [
    {'1': 'labelsDisplay', '3': 1, '4': 1, '5': 14, '6': '.WAWebProtobufsWeb.WebFeatures.Flag', '10': 'labelsDisplay'},
    {'1': 'voipIndividualOutgoing', '3': 2, '4': 1, '5': 14, '6': '.WAWebProtobufsWeb.WebFeatures.Flag', '10': 'voipIndividualOutgoing'},
    {'1': 'groupsV3', '3': 3, '4': 1, '5': 14, '6': '.WAWebProtobufsWeb.WebFeatures.Flag', '10': 'groupsV3'},
    {'1': 'groupsV3Create', '3': 4, '4': 1, '5': 14, '6': '.WAWebProtobufsWeb.WebFeatures.Flag', '10': 'groupsV3Create'},
    {'1': 'changeNumberV2', '3': 5, '4': 1, '5': 14, '6': '.WAWebProtobufsWeb.WebFeatures.Flag', '10': 'changeNumberV2'},
    {'1': 'queryStatusV3Thumbnail', '3': 6, '4': 1, '5': 14, '6': '.WAWebProtobufsWeb.WebFeatures.Flag', '10': 'queryStatusV3Thumbnail'},
    {'1': 'liveLocations', '3': 7, '4': 1, '5': 14, '6': '.WAWebProtobufsWeb.WebFeatures.Flag', '10': 'liveLocations'},
    {'1': 'queryVname', '3': 8, '4': 1, '5': 14, '6': '.WAWebProtobufsWeb.WebFeatures.Flag', '10': 'queryVname'},
    {'1': 'voipIndividualIncoming', '3': 9, '4': 1, '5': 14, '6': '.WAWebProtobufsWeb.WebFeatures.Flag', '10': 'voipIndividualIncoming'},
    {'1': 'quickRepliesQuery', '3': 10, '4': 1, '5': 14, '6': '.WAWebProtobufsWeb.WebFeatures.Flag', '10': 'quickRepliesQuery'},
    {'1': 'payments', '3': 11, '4': 1, '5': 14, '6': '.WAWebProtobufsWeb.WebFeatures.Flag', '10': 'payments'},
    {'1': 'stickerPackQuery', '3': 12, '4': 1, '5': 14, '6': '.WAWebProtobufsWeb.WebFeatures.Flag', '10': 'stickerPackQuery'},
    {'1': 'liveLocationsFinal', '3': 13, '4': 1, '5': 14, '6': '.WAWebProtobufsWeb.WebFeatures.Flag', '10': 'liveLocationsFinal'},
    {'1': 'labelsEdit', '3': 14, '4': 1, '5': 14, '6': '.WAWebProtobufsWeb.WebFeatures.Flag', '10': 'labelsEdit'},
    {'1': 'mediaUpload', '3': 15, '4': 1, '5': 14, '6': '.WAWebProtobufsWeb.WebFeatures.Flag', '10': 'mediaUpload'},
    {'1': 'mediaUploadRichQuickReplies', '3': 18, '4': 1, '5': 14, '6': '.WAWebProtobufsWeb.WebFeatures.Flag', '10': 'mediaUploadRichQuickReplies'},
    {'1': 'vnameV2', '3': 19, '4': 1, '5': 14, '6': '.WAWebProtobufsWeb.WebFeatures.Flag', '10': 'vnameV2'},
    {'1': 'videoPlaybackURL', '3': 20, '4': 1, '5': 14, '6': '.WAWebProtobufsWeb.WebFeatures.Flag', '10': 'videoPlaybackURL'},
    {'1': 'statusRanking', '3': 21, '4': 1, '5': 14, '6': '.WAWebProtobufsWeb.WebFeatures.Flag', '10': 'statusRanking'},
    {'1': 'voipIndividualVideo', '3': 22, '4': 1, '5': 14, '6': '.WAWebProtobufsWeb.WebFeatures.Flag', '10': 'voipIndividualVideo'},
    {'1': 'thirdPartyStickers', '3': 23, '4': 1, '5': 14, '6': '.WAWebProtobufsWeb.WebFeatures.Flag', '10': 'thirdPartyStickers'},
    {'1': 'frequentlyForwardedSetting', '3': 24, '4': 1, '5': 14, '6': '.WAWebProtobufsWeb.WebFeatures.Flag', '10': 'frequentlyForwardedSetting'},
    {'1': 'groupsV4JoinPermission', '3': 25, '4': 1, '5': 14, '6': '.WAWebProtobufsWeb.WebFeatures.Flag', '10': 'groupsV4JoinPermission'},
    {'1': 'recentStickers', '3': 26, '4': 1, '5': 14, '6': '.WAWebProtobufsWeb.WebFeatures.Flag', '10': 'recentStickers'},
    {'1': 'catalog', '3': 27, '4': 1, '5': 14, '6': '.WAWebProtobufsWeb.WebFeatures.Flag', '10': 'catalog'},
    {'1': 'starredStickers', '3': 28, '4': 1, '5': 14, '6': '.WAWebProtobufsWeb.WebFeatures.Flag', '10': 'starredStickers'},
    {'1': 'voipGroupCall', '3': 29, '4': 1, '5': 14, '6': '.WAWebProtobufsWeb.WebFeatures.Flag', '10': 'voipGroupCall'},
    {'1': 'templateMessage', '3': 30, '4': 1, '5': 14, '6': '.WAWebProtobufsWeb.WebFeatures.Flag', '10': 'templateMessage'},
    {'1': 'templateMessageInteractivity', '3': 31, '4': 1, '5': 14, '6': '.WAWebProtobufsWeb.WebFeatures.Flag', '10': 'templateMessageInteractivity'},
    {'1': 'ephemeralMessages', '3': 32, '4': 1, '5': 14, '6': '.WAWebProtobufsWeb.WebFeatures.Flag', '10': 'ephemeralMessages'},
    {'1': 'e2ENotificationSync', '3': 33, '4': 1, '5': 14, '6': '.WAWebProtobufsWeb.WebFeatures.Flag', '10': 'e2ENotificationSync'},
    {'1': 'recentStickersV2', '3': 34, '4': 1, '5': 14, '6': '.WAWebProtobufsWeb.WebFeatures.Flag', '10': 'recentStickersV2'},
    {'1': 'recentStickersV3', '3': 36, '4': 1, '5': 14, '6': '.WAWebProtobufsWeb.WebFeatures.Flag', '10': 'recentStickersV3'},
    {'1': 'userNotice', '3': 37, '4': 1, '5': 14, '6': '.WAWebProtobufsWeb.WebFeatures.Flag', '10': 'userNotice'},
    {'1': 'support', '3': 39, '4': 1, '5': 14, '6': '.WAWebProtobufsWeb.WebFeatures.Flag', '10': 'support'},
    {'1': 'groupUiiCleanup', '3': 40, '4': 1, '5': 14, '6': '.WAWebProtobufsWeb.WebFeatures.Flag', '10': 'groupUiiCleanup'},
    {'1': 'groupDogfoodingInternalOnly', '3': 41, '4': 1, '5': 14, '6': '.WAWebProtobufsWeb.WebFeatures.Flag', '10': 'groupDogfoodingInternalOnly'},
    {'1': 'settingsSync', '3': 42, '4': 1, '5': 14, '6': '.WAWebProtobufsWeb.WebFeatures.Flag', '10': 'settingsSync'},
    {'1': 'archiveV2', '3': 43, '4': 1, '5': 14, '6': '.WAWebProtobufsWeb.WebFeatures.Flag', '10': 'archiveV2'},
    {'1': 'ephemeralAllowGroupMembers', '3': 44, '4': 1, '5': 14, '6': '.WAWebProtobufsWeb.WebFeatures.Flag', '10': 'ephemeralAllowGroupMembers'},
    {'1': 'ephemeral24HDuration', '3': 45, '4': 1, '5': 14, '6': '.WAWebProtobufsWeb.WebFeatures.Flag', '10': 'ephemeral24HDuration'},
    {'1': 'mdForceUpgrade', '3': 46, '4': 1, '5': 14, '6': '.WAWebProtobufsWeb.WebFeatures.Flag', '10': 'mdForceUpgrade'},
    {'1': 'disappearingMode', '3': 47, '4': 1, '5': 14, '6': '.WAWebProtobufsWeb.WebFeatures.Flag', '10': 'disappearingMode'},
    {'1': 'externalMdOptInAvailable', '3': 48, '4': 1, '5': 14, '6': '.WAWebProtobufsWeb.WebFeatures.Flag', '10': 'externalMdOptInAvailable'},
    {'1': 'noDeleteMessageTimeLimit', '3': 49, '4': 1, '5': 14, '6': '.WAWebProtobufsWeb.WebFeatures.Flag', '10': 'noDeleteMessageTimeLimit'},
  ],
  '4': [WebFeatures_Flag$json],
};

@$core.Deprecated('Use webFeaturesDescriptor instead')
const WebFeatures_Flag$json = {
  '1': 'Flag',
  '2': [
    {'1': 'NOT_STARTED', '2': 0},
    {'1': 'FORCE_UPGRADE', '2': 1},
    {'1': 'DEVELOPMENT', '2': 2},
    {'1': 'PRODUCTION', '2': 3},
  ],
};

/// Descriptor for `WebFeatures`. Decode as a `google.protobuf.DescriptorProto`.
final $typed_data.Uint8List webFeaturesDescriptor = $convert.base64Decode(
    'CgtXZWJGZWF0dXJlcxJJCg1sYWJlbHNEaXNwbGF5GAEgASgOMiMuV0FXZWJQcm90b2J1ZnNXZW'
    'IuV2ViRmVhdHVyZXMuRmxhZ1INbGFiZWxzRGlzcGxheRJbChZ2b2lwSW5kaXZpZHVhbE91dGdv'
    'aW5nGAIgASgOMiMuV0FXZWJQcm90b2J1ZnNXZWIuV2ViRmVhdHVyZXMuRmxhZ1IWdm9pcEluZG'
    'l2aWR1YWxPdXRnb2luZxI/Cghncm91cHNWMxgDIAEoDjIjLldBV2ViUHJvdG9idWZzV2ViLldl'
    'YkZlYXR1cmVzLkZsYWdSCGdyb3Vwc1YzEksKDmdyb3Vwc1YzQ3JlYXRlGAQgASgOMiMuV0FXZW'
    'JQcm90b2J1ZnNXZWIuV2ViRmVhdHVyZXMuRmxhZ1IOZ3JvdXBzVjNDcmVhdGUSSwoOY2hhbmdl'
    'TnVtYmVyVjIYBSABKA4yIy5XQVdlYlByb3RvYnVmc1dlYi5XZWJGZWF0dXJlcy5GbGFnUg5jaG'
    'FuZ2VOdW1iZXJWMhJbChZxdWVyeVN0YXR1c1YzVGh1bWJuYWlsGAYgASgOMiMuV0FXZWJQcm90'
    'b2J1ZnNXZWIuV2ViRmVhdHVyZXMuRmxhZ1IWcXVlcnlTdGF0dXNWM1RodW1ibmFpbBJJCg1saX'
    'ZlTG9jYXRpb25zGAcgASgOMiMuV0FXZWJQcm90b2J1ZnNXZWIuV2ViRmVhdHVyZXMuRmxhZ1IN'
    'bGl2ZUxvY2F0aW9ucxJDCgpxdWVyeVZuYW1lGAggASgOMiMuV0FXZWJQcm90b2J1ZnNXZWIuV2'
    'ViRmVhdHVyZXMuRmxhZ1IKcXVlcnlWbmFtZRJbChZ2b2lwSW5kaXZpZHVhbEluY29taW5nGAkg'
    'ASgOMiMuV0FXZWJQcm90b2J1ZnNXZWIuV2ViRmVhdHVyZXMuRmxhZ1IWdm9pcEluZGl2aWR1YW'
    'xJbmNvbWluZxJRChFxdWlja1JlcGxpZXNRdWVyeRgKIAEoDjIjLldBV2ViUHJvdG9idWZzV2Vi'
    'LldlYkZlYXR1cmVzLkZsYWdSEXF1aWNrUmVwbGllc1F1ZXJ5Ej8KCHBheW1lbnRzGAsgASgOMi'
    'MuV0FXZWJQcm90b2J1ZnNXZWIuV2ViRmVhdHVyZXMuRmxhZ1IIcGF5bWVudHMSTwoQc3RpY2tl'
    'clBhY2tRdWVyeRgMIAEoDjIjLldBV2ViUHJvdG9idWZzV2ViLldlYkZlYXR1cmVzLkZsYWdSEH'
    'N0aWNrZXJQYWNrUXVlcnkSUwoSbGl2ZUxvY2F0aW9uc0ZpbmFsGA0gASgOMiMuV0FXZWJQcm90'
    'b2J1ZnNXZWIuV2ViRmVhdHVyZXMuRmxhZ1ISbGl2ZUxvY2F0aW9uc0ZpbmFsEkMKCmxhYmVsc0'
    'VkaXQYDiABKA4yIy5XQVdlYlByb3RvYnVmc1dlYi5XZWJGZWF0dXJlcy5GbGFnUgpsYWJlbHNF'
    'ZGl0EkUKC21lZGlhVXBsb2FkGA8gASgOMiMuV0FXZWJQcm90b2J1ZnNXZWIuV2ViRmVhdHVyZX'
    'MuRmxhZ1ILbWVkaWFVcGxvYWQSZQobbWVkaWFVcGxvYWRSaWNoUXVpY2tSZXBsaWVzGBIgASgO'
    'MiMuV0FXZWJQcm90b2J1ZnNXZWIuV2ViRmVhdHVyZXMuRmxhZ1IbbWVkaWFVcGxvYWRSaWNoUX'
    'VpY2tSZXBsaWVzEj0KB3ZuYW1lVjIYEyABKA4yIy5XQVdlYlByb3RvYnVmc1dlYi5XZWJGZWF0'
    'dXJlcy5GbGFnUgd2bmFtZVYyEk8KEHZpZGVvUGxheWJhY2tVUkwYFCABKA4yIy5XQVdlYlByb3'
    'RvYnVmc1dlYi5XZWJGZWF0dXJlcy5GbGFnUhB2aWRlb1BsYXliYWNrVVJMEkkKDXN0YXR1c1Jh'
    'bmtpbmcYFSABKA4yIy5XQVdlYlByb3RvYnVmc1dlYi5XZWJGZWF0dXJlcy5GbGFnUg1zdGF0dX'
    'NSYW5raW5nElUKE3ZvaXBJbmRpdmlkdWFsVmlkZW8YFiABKA4yIy5XQVdlYlByb3RvYnVmc1dl'
    'Yi5XZWJGZWF0dXJlcy5GbGFnUhN2b2lwSW5kaXZpZHVhbFZpZGVvElMKEnRoaXJkUGFydHlTdG'
    'lja2VycxgXIAEoDjIjLldBV2ViUHJvdG9idWZzV2ViLldlYkZlYXR1cmVzLkZsYWdSEnRoaXJk'
    'UGFydHlTdGlja2VycxJjChpmcmVxdWVudGx5Rm9yd2FyZGVkU2V0dGluZxgYIAEoDjIjLldBV2'
    'ViUHJvdG9idWZzV2ViLldlYkZlYXR1cmVzLkZsYWdSGmZyZXF1ZW50bHlGb3J3YXJkZWRTZXR0'
    'aW5nElsKFmdyb3Vwc1Y0Sm9pblBlcm1pc3Npb24YGSABKA4yIy5XQVdlYlByb3RvYnVmc1dlYi'
    '5XZWJGZWF0dXJlcy5GbGFnUhZncm91cHNWNEpvaW5QZXJtaXNzaW9uEksKDnJlY2VudFN0aWNr'
    'ZXJzGBogASgOMiMuV0FXZWJQcm90b2J1ZnNXZWIuV2ViRmVhdHVyZXMuRmxhZ1IOcmVjZW50U3'
    'RpY2tlcnMSPQoHY2F0YWxvZxgbIAEoDjIjLldBV2ViUHJvdG9idWZzV2ViLldlYkZlYXR1cmVz'
    'LkZsYWdSB2NhdGFsb2cSTQoPc3RhcnJlZFN0aWNrZXJzGBwgASgOMiMuV0FXZWJQcm90b2J1Zn'
    'NXZWIuV2ViRmVhdHVyZXMuRmxhZ1IPc3RhcnJlZFN0aWNrZXJzEkkKDXZvaXBHcm91cENhbGwY'
    'HSABKA4yIy5XQVdlYlByb3RvYnVmc1dlYi5XZWJGZWF0dXJlcy5GbGFnUg12b2lwR3JvdXBDYW'
    'xsEk0KD3RlbXBsYXRlTWVzc2FnZRgeIAEoDjIjLldBV2ViUHJvdG9idWZzV2ViLldlYkZlYXR1'
    'cmVzLkZsYWdSD3RlbXBsYXRlTWVzc2FnZRJnChx0ZW1wbGF0ZU1lc3NhZ2VJbnRlcmFjdGl2aX'
    'R5GB8gASgOMiMuV0FXZWJQcm90b2J1ZnNXZWIuV2ViRmVhdHVyZXMuRmxhZ1IcdGVtcGxhdGVN'
    'ZXNzYWdlSW50ZXJhY3Rpdml0eRJRChFlcGhlbWVyYWxNZXNzYWdlcxggIAEoDjIjLldBV2ViUH'
    'JvdG9idWZzV2ViLldlYkZlYXR1cmVzLkZsYWdSEWVwaGVtZXJhbE1lc3NhZ2VzElUKE2UyRU5v'
    'dGlmaWNhdGlvblN5bmMYISABKA4yIy5XQVdlYlByb3RvYnVmc1dlYi5XZWJGZWF0dXJlcy5GbG'
    'FnUhNlMkVOb3RpZmljYXRpb25TeW5jEk8KEHJlY2VudFN0aWNrZXJzVjIYIiABKA4yIy5XQVdl'
    'YlByb3RvYnVmc1dlYi5XZWJGZWF0dXJlcy5GbGFnUhByZWNlbnRTdGlja2Vyc1YyEk8KEHJlY2'
    'VudFN0aWNrZXJzVjMYJCABKA4yIy5XQVdlYlByb3RvYnVmc1dlYi5XZWJGZWF0dXJlcy5GbGFn'
    'UhByZWNlbnRTdGlja2Vyc1YzEkMKCnVzZXJOb3RpY2UYJSABKA4yIy5XQVdlYlByb3RvYnVmc1'
    'dlYi5XZWJGZWF0dXJlcy5GbGFnUgp1c2VyTm90aWNlEj0KB3N1cHBvcnQYJyABKA4yIy5XQVdl'
    'YlByb3RvYnVmc1dlYi5XZWJGZWF0dXJlcy5GbGFnUgdzdXBwb3J0Ek0KD2dyb3VwVWlpQ2xlYW'
    '51cBgoIAEoDjIjLldBV2ViUHJvdG9idWZzV2ViLldlYkZlYXR1cmVzLkZsYWdSD2dyb3VwVWlp'
    'Q2xlYW51cBJlChtncm91cERvZ2Zvb2RpbmdJbnRlcm5hbE9ubHkYKSABKA4yIy5XQVdlYlByb3'
    'RvYnVmc1dlYi5XZWJGZWF0dXJlcy5GbGFnUhtncm91cERvZ2Zvb2RpbmdJbnRlcm5hbE9ubHkS'
    'RwoMc2V0dGluZ3NTeW5jGCogASgOMiMuV0FXZWJQcm90b2J1ZnNXZWIuV2ViRmVhdHVyZXMuRm'
    'xhZ1IMc2V0dGluZ3NTeW5jEkEKCWFyY2hpdmVWMhgrIAEoDjIjLldBV2ViUHJvdG9idWZzV2Vi'
    'LldlYkZlYXR1cmVzLkZsYWdSCWFyY2hpdmVWMhJjChplcGhlbWVyYWxBbGxvd0dyb3VwTWVtYm'
    'VycxgsIAEoDjIjLldBV2ViUHJvdG9idWZzV2ViLldlYkZlYXR1cmVzLkZsYWdSGmVwaGVtZXJh'
    'bEFsbG93R3JvdXBNZW1iZXJzElcKFGVwaGVtZXJhbDI0SER1cmF0aW9uGC0gASgOMiMuV0FXZW'
    'JQcm90b2J1ZnNXZWIuV2ViRmVhdHVyZXMuRmxhZ1IUZXBoZW1lcmFsMjRIRHVyYXRpb24SSwoO'
    'bWRGb3JjZVVwZ3JhZGUYLiABKA4yIy5XQVdlYlByb3RvYnVmc1dlYi5XZWJGZWF0dXJlcy5GbG'
    'FnUg5tZEZvcmNlVXBncmFkZRJPChBkaXNhcHBlYXJpbmdNb2RlGC8gASgOMiMuV0FXZWJQcm90'
    'b2J1ZnNXZWIuV2ViRmVhdHVyZXMuRmxhZ1IQZGlzYXBwZWFyaW5nTW9kZRJfChhleHRlcm5hbE'
    '1kT3B0SW5BdmFpbGFibGUYMCABKA4yIy5XQVdlYlByb3RvYnVmc1dlYi5XZWJGZWF0dXJlcy5G'
    'bGFnUhhleHRlcm5hbE1kT3B0SW5BdmFpbGFibGUSXwoYbm9EZWxldGVNZXNzYWdlVGltZUxpbW'
    'l0GDEgASgOMiMuV0FXZWJQcm90b2J1ZnNXZWIuV2ViRmVhdHVyZXMuRmxhZ1IYbm9EZWxldGVN'
    'ZXNzYWdlVGltZUxpbWl0IksKBEZsYWcSDwoLTk9UX1NUQVJURUQQABIRCg1GT1JDRV9VUEdSQU'
    'RFEAESDwoLREVWRUxPUE1FTlQQAhIOCgpQUk9EVUNUSU9OEAM=');

@$core.Deprecated('Use pinInChatDescriptor instead')
const PinInChat$json = {
  '1': 'PinInChat',
  '2': [
    {'1': 'type', '3': 1, '4': 1, '5': 14, '6': '.WAWebProtobufsWeb.PinInChat.Type', '10': 'type'},
    {'1': 'key', '3': 2, '4': 1, '5': 11, '6': '.WACommon.MessageKey', '10': 'key'},
    {'1': 'senderTimestampMS', '3': 3, '4': 1, '5': 3, '10': 'senderTimestampMS'},
    {'1': 'serverTimestampMS', '3': 4, '4': 1, '5': 3, '10': 'serverTimestampMS'},
    {'1': 'messageAddOnContextInfo', '3': 5, '4': 1, '5': 11, '6': '.WAWebProtobufsWeb.MessageAddOnContextInfo', '10': 'messageAddOnContextInfo'},
  ],
  '4': [PinInChat_Type$json],
};

@$core.Deprecated('Use pinInChatDescriptor instead')
const PinInChat_Type$json = {
  '1': 'Type',
  '2': [
    {'1': 'UNKNOWN_TYPE', '2': 0},
    {'1': 'PIN_FOR_ALL', '2': 1},
    {'1': 'UNPIN_FOR_ALL', '2': 2},
  ],
};

/// Descriptor for `PinInChat`. Decode as a `google.protobuf.DescriptorProto`.
final $typed_data.Uint8List pinInChatDescriptor = $convert.base64Decode(
    'CglQaW5JbkNoYXQSNQoEdHlwZRgBIAEoDjIhLldBV2ViUHJvdG9idWZzV2ViLlBpbkluQ2hhdC'
    '5UeXBlUgR0eXBlEiYKA2tleRgCIAEoCzIULldBQ29tbW9uLk1lc3NhZ2VLZXlSA2tleRIsChFz'
    'ZW5kZXJUaW1lc3RhbXBNUxgDIAEoA1IRc2VuZGVyVGltZXN0YW1wTVMSLAoRc2VydmVyVGltZX'
    'N0YW1wTVMYBCABKANSEXNlcnZlclRpbWVzdGFtcE1TEmQKF21lc3NhZ2VBZGRPbkNvbnRleHRJ'
    'bmZvGAUgASgLMiouV0FXZWJQcm90b2J1ZnNXZWIuTWVzc2FnZUFkZE9uQ29udGV4dEluZm9SF2'
    '1lc3NhZ2VBZGRPbkNvbnRleHRJbmZvIjwKBFR5cGUSEAoMVU5LTk9XTl9UWVBFEAASDwoLUElO'
    'X0ZPUl9BTEwQARIRCg1VTlBJTl9GT1JfQUxMEAI=');

@$core.Deprecated('Use messageAddOnDescriptor instead')
const MessageAddOn$json = {
  '1': 'MessageAddOn',
  '2': [
    {'1': 'messageAddOnType', '3': 1, '4': 1, '5': 14, '6': '.WAWebProtobufsWeb.MessageAddOn.MessageAddOnType', '10': 'messageAddOnType'},
    {'1': 'messageAddOn', '3': 2, '4': 1, '5': 11, '6': '.WAWebProtobufsE2E.Message', '10': 'messageAddOn'},
    {'1': 'senderTimestampMS', '3': 3, '4': 1, '5': 3, '10': 'senderTimestampMS'},
    {'1': 'serverTimestampMS', '3': 4, '4': 1, '5': 3, '10': 'serverTimestampMS'},
    {'1': 'status', '3': 5, '4': 1, '5': 14, '6': '.WAWebProtobufsWeb.WebMessageInfo.Status', '10': 'status'},
    {'1': 'addOnContextInfo', '3': 6, '4': 1, '5': 11, '6': '.WAWebProtobufsWeb.MessageAddOnContextInfo', '10': 'addOnContextInfo'},
    {'1': 'messageAddOnKey', '3': 7, '4': 1, '5': 11, '6': '.WACommon.MessageKey', '10': 'messageAddOnKey'},
    {'1': 'legacyMessage', '3': 8, '4': 1, '5': 11, '6': '.WAWebProtobufsWeb.LegacyMessage', '10': 'legacyMessage'},
  ],
  '4': [MessageAddOn_MessageAddOnType$json],
};

@$core.Deprecated('Use messageAddOnDescriptor instead')
const MessageAddOn_MessageAddOnType$json = {
  '1': 'MessageAddOnType',
  '2': [
    {'1': 'UNDEFINED', '2': 0},
    {'1': 'REACTION', '2': 1},
    {'1': 'EVENT_RESPONSE', '2': 2},
    {'1': 'POLL_UPDATE', '2': 3},
    {'1': 'PIN_IN_CHAT', '2': 4},
  ],
};

/// Descriptor for `MessageAddOn`. Decode as a `google.protobuf.DescriptorProto`.
final $typed_data.Uint8List messageAddOnDescriptor = $convert.base64Decode(
    'CgxNZXNzYWdlQWRkT24SXAoQbWVzc2FnZUFkZE9uVHlwZRgBIAEoDjIwLldBV2ViUHJvdG9idW'
    'ZzV2ViLk1lc3NhZ2VBZGRPbi5NZXNzYWdlQWRkT25UeXBlUhBtZXNzYWdlQWRkT25UeXBlEj4K'
    'DG1lc3NhZ2VBZGRPbhgCIAEoCzIaLldBV2ViUHJvdG9idWZzRTJFLk1lc3NhZ2VSDG1lc3NhZ2'
    'VBZGRPbhIsChFzZW5kZXJUaW1lc3RhbXBNUxgDIAEoA1IRc2VuZGVyVGltZXN0YW1wTVMSLAoR'
    'c2VydmVyVGltZXN0YW1wTVMYBCABKANSEXNlcnZlclRpbWVzdGFtcE1TEkAKBnN0YXR1cxgFIA'
    'EoDjIoLldBV2ViUHJvdG9idWZzV2ViLldlYk1lc3NhZ2VJbmZvLlN0YXR1c1IGc3RhdHVzElYK'
    'EGFkZE9uQ29udGV4dEluZm8YBiABKAsyKi5XQVdlYlByb3RvYnVmc1dlYi5NZXNzYWdlQWRkT2'
    '5Db250ZXh0SW5mb1IQYWRkT25Db250ZXh0SW5mbxI+Cg9tZXNzYWdlQWRkT25LZXkYByABKAsy'
    'FC5XQUNvbW1vbi5NZXNzYWdlS2V5Ug9tZXNzYWdlQWRkT25LZXkSRgoNbGVnYWN5TWVzc2FnZR'
    'gIIAEoCzIgLldBV2ViUHJvdG9idWZzV2ViLkxlZ2FjeU1lc3NhZ2VSDWxlZ2FjeU1lc3NhZ2Ui'
    'ZQoQTWVzc2FnZUFkZE9uVHlwZRINCglVTkRFRklORUQQABIMCghSRUFDVElPThABEhIKDkVWRU'
    '5UX1JFU1BPTlNFEAISDwoLUE9MTF9VUERBVEUQAxIPCgtQSU5fSU5fQ0hBVBAE');

@$core.Deprecated('Use commentMetadataDescriptor instead')
const CommentMetadata$json = {
  '1': 'CommentMetadata',
  '2': [
    {'1': 'commentParentKey', '3': 1, '4': 1, '5': 11, '6': '.WACommon.MessageKey', '10': 'commentParentKey'},
    {'1': 'replyCount', '3': 2, '4': 1, '5': 13, '10': 'replyCount'},
  ],
};

/// Descriptor for `CommentMetadata`. Decode as a `google.protobuf.DescriptorProto`.
final $typed_data.Uint8List commentMetadataDescriptor = $convert.base64Decode(
    'Cg9Db21tZW50TWV0YWRhdGESQAoQY29tbWVudFBhcmVudEtleRgBIAEoCzIULldBQ29tbW9uLk'
    '1lc3NhZ2VLZXlSEGNvbW1lbnRQYXJlbnRLZXkSHgoKcmVwbHlDb3VudBgCIAEoDVIKcmVwbHlD'
    'b3VudA==');

@$core.Deprecated('Use webNotificationsInfoDescriptor instead')
const WebNotificationsInfo$json = {
  '1': 'WebNotificationsInfo',
  '2': [
    {'1': 'timestamp', '3': 2, '4': 1, '5': 4, '10': 'timestamp'},
    {'1': 'unreadChats', '3': 3, '4': 1, '5': 13, '10': 'unreadChats'},
    {'1': 'notifyMessageCount', '3': 4, '4': 1, '5': 13, '10': 'notifyMessageCount'},
    {'1': 'notifyMessages', '3': 5, '4': 3, '5': 11, '6': '.WAWebProtobufsWeb.WebMessageInfo', '10': 'notifyMessages'},
  ],
};

/// Descriptor for `WebNotificationsInfo`. Decode as a `google.protobuf.DescriptorProto`.
final $typed_data.Uint8List webNotificationsInfoDescriptor = $convert.base64Decode(
    'ChRXZWJOb3RpZmljYXRpb25zSW5mbxIcCgl0aW1lc3RhbXAYAiABKARSCXRpbWVzdGFtcBIgCg'
    't1bnJlYWRDaGF0cxgDIAEoDVILdW5yZWFkQ2hhdHMSLgoSbm90aWZ5TWVzc2FnZUNvdW50GAQg'
    'ASgNUhJub3RpZnlNZXNzYWdlQ291bnQSSQoObm90aWZ5TWVzc2FnZXMYBSADKAsyIS5XQVdlYl'
    'Byb3RvYnVmc1dlYi5XZWJNZXNzYWdlSW5mb1IObm90aWZ5TWVzc2FnZXM=');

@$core.Deprecated('Use notificationMessageInfoDescriptor instead')
const NotificationMessageInfo$json = {
  '1': 'NotificationMessageInfo',
  '2': [
    {'1': 'key', '3': 1, '4': 1, '5': 11, '6': '.WACommon.MessageKey', '10': 'key'},
    {'1': 'message', '3': 2, '4': 1, '5': 11, '6': '.WAWebProtobufsE2E.Message', '10': 'message'},
    {'1': 'messageTimestamp', '3': 3, '4': 1, '5': 4, '10': 'messageTimestamp'},
    {'1': 'participant', '3': 4, '4': 1, '5': 9, '10': 'participant'},
  ],
};

/// Descriptor for `NotificationMessageInfo`. Decode as a `google.protobuf.DescriptorProto`.
final $typed_data.Uint8List notificationMessageInfoDescriptor = $convert.base64Decode(
    'ChdOb3RpZmljYXRpb25NZXNzYWdlSW5mbxImCgNrZXkYASABKAsyFC5XQUNvbW1vbi5NZXNzYW'
    'dlS2V5UgNrZXkSNAoHbWVzc2FnZRgCIAEoCzIaLldBV2ViUHJvdG9idWZzRTJFLk1lc3NhZ2VS'
    'B21lc3NhZ2USKgoQbWVzc2FnZVRpbWVzdGFtcBgDIAEoBFIQbWVzc2FnZVRpbWVzdGFtcBIgCg'
    'twYXJ0aWNpcGFudBgEIAEoCVILcGFydGljaXBhbnQ=');

@$core.Deprecated('Use reportingTokenInfoDescriptor instead')
const ReportingTokenInfo$json = {
  '1': 'ReportingTokenInfo',
  '2': [
    {'1': 'reportingTag', '3': 1, '4': 1, '5': 12, '10': 'reportingTag'},
  ],
};

/// Descriptor for `ReportingTokenInfo`. Decode as a `google.protobuf.DescriptorProto`.
final $typed_data.Uint8List reportingTokenInfoDescriptor = $convert.base64Decode(
    'ChJSZXBvcnRpbmdUb2tlbkluZm8SIgoMcmVwb3J0aW5nVGFnGAEgASgMUgxyZXBvcnRpbmdUYW'
    'c=');

@$core.Deprecated('Use mediaDataDescriptor instead')
const MediaData$json = {
  '1': 'MediaData',
  '2': [
    {'1': 'localPath', '3': 1, '4': 1, '5': 9, '10': 'localPath'},
  ],
};

/// Descriptor for `MediaData`. Decode as a `google.protobuf.DescriptorProto`.
final $typed_data.Uint8List mediaDataDescriptor = $convert.base64Decode(
    'CglNZWRpYURhdGESHAoJbG9jYWxQYXRoGAEgASgJUglsb2NhbFBhdGg=');

@$core.Deprecated('Use photoChangeDescriptor instead')
const PhotoChange$json = {
  '1': 'PhotoChange',
  '2': [
    {'1': 'oldPhoto', '3': 1, '4': 1, '5': 12, '10': 'oldPhoto'},
    {'1': 'newPhoto', '3': 2, '4': 1, '5': 12, '10': 'newPhoto'},
    {'1': 'newPhotoID', '3': 3, '4': 1, '5': 13, '10': 'newPhotoID'},
  ],
};

/// Descriptor for `PhotoChange`. Decode as a `google.protobuf.DescriptorProto`.
final $typed_data.Uint8List photoChangeDescriptor = $convert.base64Decode(
    'CgtQaG90b0NoYW5nZRIaCghvbGRQaG90bxgBIAEoDFIIb2xkUGhvdG8SGgoIbmV3UGhvdG8YAi'
    'ABKAxSCG5ld1Bob3RvEh4KCm5ld1Bob3RvSUQYAyABKA1SCm5ld1Bob3RvSUQ=');

@$core.Deprecated('Use statusPSADescriptor instead')
const StatusPSA$json = {
  '1': 'StatusPSA',
  '2': [
    {'1': 'campaignID', '3': 44, '4': 2, '5': 4, '10': 'campaignID'},
    {'1': 'campaignExpirationTimestamp', '3': 45, '4': 1, '5': 4, '10': 'campaignExpirationTimestamp'},
  ],
};

/// Descriptor for `StatusPSA`. Decode as a `google.protobuf.DescriptorProto`.
final $typed_data.Uint8List statusPSADescriptor = $convert.base64Decode(
    'CglTdGF0dXNQU0ESHgoKY2FtcGFpZ25JRBgsIAIoBFIKY2FtcGFpZ25JRBJAChtjYW1wYWlnbk'
    'V4cGlyYXRpb25UaW1lc3RhbXAYLSABKARSG2NhbXBhaWduRXhwaXJhdGlvblRpbWVzdGFtcA==');

@$core.Deprecated('Use userReceiptDescriptor instead')
const UserReceipt$json = {
  '1': 'UserReceipt',
  '2': [
    {'1': 'userJID', '3': 1, '4': 2, '5': 9, '10': 'userJID'},
    {'1': 'receiptTimestamp', '3': 2, '4': 1, '5': 3, '10': 'receiptTimestamp'},
    {'1': 'readTimestamp', '3': 3, '4': 1, '5': 3, '10': 'readTimestamp'},
    {'1': 'playedTimestamp', '3': 4, '4': 1, '5': 3, '10': 'playedTimestamp'},
    {'1': 'pendingDeviceJID', '3': 5, '4': 3, '5': 9, '10': 'pendingDeviceJID'},
    {'1': 'deliveredDeviceJID', '3': 6, '4': 3, '5': 9, '10': 'deliveredDeviceJID'},
  ],
};

/// Descriptor for `UserReceipt`. Decode as a `google.protobuf.DescriptorProto`.
final $typed_data.Uint8List userReceiptDescriptor = $convert.base64Decode(
    'CgtVc2VyUmVjZWlwdBIYCgd1c2VySklEGAEgAigJUgd1c2VySklEEioKEHJlY2VpcHRUaW1lc3'
    'RhbXAYAiABKANSEHJlY2VpcHRUaW1lc3RhbXASJAoNcmVhZFRpbWVzdGFtcBgDIAEoA1INcmVh'
    'ZFRpbWVzdGFtcBIoCg9wbGF5ZWRUaW1lc3RhbXAYBCABKANSD3BsYXllZFRpbWVzdGFtcBIqCh'
    'BwZW5kaW5nRGV2aWNlSklEGAUgAygJUhBwZW5kaW5nRGV2aWNlSklEEi4KEmRlbGl2ZXJlZERl'
    'dmljZUpJRBgGIAMoCVISZGVsaXZlcmVkRGV2aWNlSklE');

@$core.Deprecated('Use reactionDescriptor instead')
const Reaction$json = {
  '1': 'Reaction',
  '2': [
    {'1': 'key', '3': 1, '4': 1, '5': 11, '6': '.WACommon.MessageKey', '10': 'key'},
    {'1': 'text', '3': 2, '4': 1, '5': 9, '10': 'text'},
    {'1': 'groupingKey', '3': 3, '4': 1, '5': 9, '10': 'groupingKey'},
    {'1': 'senderTimestampMS', '3': 4, '4': 1, '5': 3, '10': 'senderTimestampMS'},
    {'1': 'unread', '3': 5, '4': 1, '5': 8, '10': 'unread'},
  ],
};

/// Descriptor for `Reaction`. Decode as a `google.protobuf.DescriptorProto`.
final $typed_data.Uint8List reactionDescriptor = $convert.base64Decode(
    'CghSZWFjdGlvbhImCgNrZXkYASABKAsyFC5XQUNvbW1vbi5NZXNzYWdlS2V5UgNrZXkSEgoEdG'
    'V4dBgCIAEoCVIEdGV4dBIgCgtncm91cGluZ0tleRgDIAEoCVILZ3JvdXBpbmdLZXkSLAoRc2Vu'
    'ZGVyVGltZXN0YW1wTVMYBCABKANSEXNlbmRlclRpbWVzdGFtcE1TEhYKBnVucmVhZBgFIAEoCF'
    'IGdW5yZWFk');

@$core.Deprecated('Use pollUpdateDescriptor instead')
const PollUpdate$json = {
  '1': 'PollUpdate',
  '2': [
    {'1': 'pollUpdateMessageKey', '3': 1, '4': 1, '5': 11, '6': '.WACommon.MessageKey', '10': 'pollUpdateMessageKey'},
    {'1': 'vote', '3': 2, '4': 1, '5': 11, '6': '.WAWebProtobufsE2E.PollVoteMessage', '10': 'vote'},
    {'1': 'senderTimestampMS', '3': 3, '4': 1, '5': 3, '10': 'senderTimestampMS'},
    {'1': 'serverTimestampMS', '3': 4, '4': 1, '5': 3, '10': 'serverTimestampMS'},
    {'1': 'unread', '3': 5, '4': 1, '5': 8, '10': 'unread'},
  ],
};

/// Descriptor for `PollUpdate`. Decode as a `google.protobuf.DescriptorProto`.
final $typed_data.Uint8List pollUpdateDescriptor = $convert.base64Decode(
    'CgpQb2xsVXBkYXRlEkgKFHBvbGxVcGRhdGVNZXNzYWdlS2V5GAEgASgLMhQuV0FDb21tb24uTW'
    'Vzc2FnZUtleVIUcG9sbFVwZGF0ZU1lc3NhZ2VLZXkSNgoEdm90ZRgCIAEoCzIiLldBV2ViUHJv'
    'dG9idWZzRTJFLlBvbGxWb3RlTWVzc2FnZVIEdm90ZRIsChFzZW5kZXJUaW1lc3RhbXBNUxgDIA'
    'EoA1IRc2VuZGVyVGltZXN0YW1wTVMSLAoRc2VydmVyVGltZXN0YW1wTVMYBCABKANSEXNlcnZl'
    'clRpbWVzdGFtcE1TEhYKBnVucmVhZBgFIAEoCFIGdW5yZWFk');

@$core.Deprecated('Use pollAdditionalMetadataDescriptor instead')
const PollAdditionalMetadata$json = {
  '1': 'PollAdditionalMetadata',
  '2': [
    {'1': 'pollInvalidated', '3': 1, '4': 1, '5': 8, '10': 'pollInvalidated'},
  ],
};

/// Descriptor for `PollAdditionalMetadata`. Decode as a `google.protobuf.DescriptorProto`.
final $typed_data.Uint8List pollAdditionalMetadataDescriptor = $convert.base64Decode(
    'ChZQb2xsQWRkaXRpb25hbE1ldGFkYXRhEigKD3BvbGxJbnZhbGlkYXRlZBgBIAEoCFIPcG9sbE'
    'ludmFsaWRhdGVk');

@$core.Deprecated('Use eventAdditionalMetadataDescriptor instead')
const EventAdditionalMetadata$json = {
  '1': 'EventAdditionalMetadata',
  '2': [
    {'1': 'isStale', '3': 1, '4': 1, '5': 8, '10': 'isStale'},
  ],
};

/// Descriptor for `EventAdditionalMetadata`. Decode as a `google.protobuf.DescriptorProto`.
final $typed_data.Uint8List eventAdditionalMetadataDescriptor = $convert.base64Decode(
    'ChdFdmVudEFkZGl0aW9uYWxNZXRhZGF0YRIYCgdpc1N0YWxlGAEgASgIUgdpc1N0YWxl');

@$core.Deprecated('Use keepInChatDescriptor instead')
const KeepInChat$json = {
  '1': 'KeepInChat',
  '2': [
    {'1': 'keepType', '3': 1, '4': 1, '5': 14, '6': '.WAWebProtobufsE2E.KeepType', '10': 'keepType'},
    {'1': 'serverTimestamp', '3': 2, '4': 1, '5': 3, '10': 'serverTimestamp'},
    {'1': 'key', '3': 3, '4': 1, '5': 11, '6': '.WACommon.MessageKey', '10': 'key'},
    {'1': 'deviceJID', '3': 4, '4': 1, '5': 9, '10': 'deviceJID'},
    {'1': 'clientTimestampMS', '3': 5, '4': 1, '5': 3, '10': 'clientTimestampMS'},
    {'1': 'serverTimestampMS', '3': 6, '4': 1, '5': 3, '10': 'serverTimestampMS'},
  ],
};

/// Descriptor for `KeepInChat`. Decode as a `google.protobuf.DescriptorProto`.
final $typed_data.Uint8List keepInChatDescriptor = $convert.base64Decode(
    'CgpLZWVwSW5DaGF0EjcKCGtlZXBUeXBlGAEgASgOMhsuV0FXZWJQcm90b2J1ZnNFMkUuS2VlcF'
    'R5cGVSCGtlZXBUeXBlEigKD3NlcnZlclRpbWVzdGFtcBgCIAEoA1IPc2VydmVyVGltZXN0YW1w'
    'EiYKA2tleRgDIAEoCzIULldBQ29tbW9uLk1lc3NhZ2VLZXlSA2tleRIcCglkZXZpY2VKSUQYBC'
    'ABKAlSCWRldmljZUpJRBIsChFjbGllbnRUaW1lc3RhbXBNUxgFIAEoA1IRY2xpZW50VGltZXN0'
    'YW1wTVMSLAoRc2VydmVyVGltZXN0YW1wTVMYBiABKANSEXNlcnZlclRpbWVzdGFtcE1T');

@$core.Deprecated('Use messageAddOnContextInfoDescriptor instead')
const MessageAddOnContextInfo$json = {
  '1': 'MessageAddOnContextInfo',
  '2': [
    {'1': 'messageAddOnDurationInSecs', '3': 1, '4': 1, '5': 13, '10': 'messageAddOnDurationInSecs'},
    {'1': 'messageAddOnExpiryType', '3': 2, '4': 1, '5': 14, '6': '.WAWebProtobufsE2E.MessageContextInfo.MessageAddonExpiryType', '10': 'messageAddOnExpiryType'},
  ],
};

/// Descriptor for `MessageAddOnContextInfo`. Decode as a `google.protobuf.DescriptorProto`.
final $typed_data.Uint8List messageAddOnContextInfoDescriptor = $convert.base64Decode(
    'ChdNZXNzYWdlQWRkT25Db250ZXh0SW5mbxI+ChptZXNzYWdlQWRkT25EdXJhdGlvbkluU2Vjcx'
    'gBIAEoDVIabWVzc2FnZUFkZE9uRHVyYXRpb25JblNlY3MSdAoWbWVzc2FnZUFkZE9uRXhwaXJ5'
    'VHlwZRgCIAEoDjI8LldBV2ViUHJvdG9idWZzRTJFLk1lc3NhZ2VDb250ZXh0SW5mby5NZXNzYW'
    'dlQWRkb25FeHBpcnlUeXBlUhZtZXNzYWdlQWRkT25FeHBpcnlUeXBl');

@$core.Deprecated('Use premiumMessageInfoDescriptor instead')
const PremiumMessageInfo$json = {
  '1': 'PremiumMessageInfo',
  '2': [
    {'1': 'serverCampaignID', '3': 1, '4': 1, '5': 9, '10': 'serverCampaignID'},
  ],
};

/// Descriptor for `PremiumMessageInfo`. Decode as a `google.protobuf.DescriptorProto`.
final $typed_data.Uint8List premiumMessageInfoDescriptor = $convert.base64Decode(
    'ChJQcmVtaXVtTWVzc2FnZUluZm8SKgoQc2VydmVyQ2FtcGFpZ25JRBgBIAEoCVIQc2VydmVyQ2'
    'FtcGFpZ25JRA==');

@$core.Deprecated('Use eventResponseDescriptor instead')
const EventResponse$json = {
  '1': 'EventResponse',
  '2': [
    {'1': 'eventResponseMessageKey', '3': 1, '4': 1, '5': 11, '6': '.WACommon.MessageKey', '10': 'eventResponseMessageKey'},
    {'1': 'timestampMS', '3': 2, '4': 1, '5': 3, '10': 'timestampMS'},
    {'1': 'eventResponseMessage', '3': 3, '4': 1, '5': 11, '6': '.WAWebProtobufsE2E.EventResponseMessage', '10': 'eventResponseMessage'},
    {'1': 'unread', '3': 4, '4': 1, '5': 8, '10': 'unread'},
  ],
};

/// Descriptor for `EventResponse`. Decode as a `google.protobuf.DescriptorProto`.
final $typed_data.Uint8List eventResponseDescriptor = $convert.base64Decode(
    'Cg1FdmVudFJlc3BvbnNlEk4KF2V2ZW50UmVzcG9uc2VNZXNzYWdlS2V5GAEgASgLMhQuV0FDb2'
    '1tb24uTWVzc2FnZUtleVIXZXZlbnRSZXNwb25zZU1lc3NhZ2VLZXkSIAoLdGltZXN0YW1wTVMY'
    'AiABKANSC3RpbWVzdGFtcE1TElsKFGV2ZW50UmVzcG9uc2VNZXNzYWdlGAMgASgLMicuV0FXZW'
    'JQcm90b2J1ZnNFMkUuRXZlbnRSZXNwb25zZU1lc3NhZ2VSFGV2ZW50UmVzcG9uc2VNZXNzYWdl'
    'EhYKBnVucmVhZBgEIAEoCFIGdW5yZWFk');

@$core.Deprecated('Use legacyMessageDescriptor instead')
const LegacyMessage$json = {
  '1': 'LegacyMessage',
  '2': [
    {'1': 'eventResponseMessage', '3': 1, '4': 1, '5': 11, '6': '.WAWebProtobufsE2E.EventResponseMessage', '10': 'eventResponseMessage'},
    {'1': 'pollVote', '3': 2, '4': 1, '5': 11, '6': '.WAWebProtobufsE2E.PollVoteMessage', '10': 'pollVote'},
  ],
};

/// Descriptor for `LegacyMessage`. Decode as a `google.protobuf.DescriptorProto`.
final $typed_data.Uint8List legacyMessageDescriptor = $convert.base64Decode(
    'Cg1MZWdhY3lNZXNzYWdlElsKFGV2ZW50UmVzcG9uc2VNZXNzYWdlGAEgASgLMicuV0FXZWJQcm'
    '90b2J1ZnNFMkUuRXZlbnRSZXNwb25zZU1lc3NhZ2VSFGV2ZW50UmVzcG9uc2VNZXNzYWdlEj4K'
    'CHBvbGxWb3RlGAIgASgLMiIuV0FXZWJQcm90b2J1ZnNFMkUuUG9sbFZvdGVNZXNzYWdlUghwb2'
    'xsVm90ZQ==');

@$core.Deprecated('Use statusMentionMessageDescriptor instead')
const StatusMentionMessage$json = {
  '1': 'StatusMentionMessage',
  '2': [
    {'1': 'quotedStatus', '3': 1, '4': 1, '5': 11, '6': '.WAWebProtobufsE2E.Message', '10': 'quotedStatus'},
  ],
};

/// Descriptor for `StatusMentionMessage`. Decode as a `google.protobuf.DescriptorProto`.
final $typed_data.Uint8List statusMentionMessageDescriptor = $convert.base64Decode(
    'ChRTdGF0dXNNZW50aW9uTWVzc2FnZRI+CgxxdW90ZWRTdGF0dXMYASABKAsyGi5XQVdlYlByb3'
    'RvYnVmc0UyRS5NZXNzYWdlUgxxdW90ZWRTdGF0dXM=');

@$core.Deprecated('Use citationDescriptor instead')
const Citation$json = {
  '1': 'Citation',
  '2': [
    {'1': 'title', '3': 1, '4': 2, '5': 9, '10': 'title'},
    {'1': 'subtitle', '3': 2, '4': 2, '5': 9, '10': 'subtitle'},
    {'1': 'cmsID', '3': 3, '4': 2, '5': 9, '10': 'cmsID'},
    {'1': 'imageURL', '3': 4, '4': 2, '5': 9, '10': 'imageURL'},
  ],
};

/// Descriptor for `Citation`. Decode as a `google.protobuf.DescriptorProto`.
final $typed_data.Uint8List citationDescriptor = $convert.base64Decode(
    'CghDaXRhdGlvbhIUCgV0aXRsZRgBIAIoCVIFdGl0bGUSGgoIc3VidGl0bGUYAiACKAlSCHN1Yn'
    'RpdGxlEhQKBWNtc0lEGAMgAigJUgVjbXNJRBIaCghpbWFnZVVSTBgEIAIoCVIIaW1hZ2VVUkw=');

